USE [EHI_LIVE_LATEST]
GO
/****** OBJECT:  STOREDPROCEDURE [DBO].[SBO_SP_TRANSACTIONNOTIFICATION]    SCRIPT DATE: SEP 13, 2021 10:48:44 AM ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
--USE [EHI_LIVE_1025]
--GO
--/****** OBJECT:  STOREDPROCEDURE [DBO].[SBO_SP_TRANSACTIONNOTIFICATION]    SCRIPT DATE: 10/26/2020 7:27:28 AM ******/
--SET ANSI_NULLS ON
--GO
--SET QUOTED_IDENTIFIER ON
--GO
----USE [EHI_TEST]
--GO
--/****** OBJECT:  STOREDPROCEDURE [DBO].[SBO_SP_TRANSACTIONNOTIFICATION]    SCRIPT DATE: 10/19/2020 10:46:49 AM ******/
--SET ANSI_NULLS ONGOODS
--GO
--SET QUOTED_IDENTIFIER ON
--GO
----USE [EHI_TEST]
----GO
----/****** OBJECT:  STOREDPROCEDURE [DBO].[SBO_SP_TRANSACTIONNOTIFICATION]    SCRIPT DATE: 10/15/2020 8:13:17 PM ******/
----SET ANSI_NULLS ON
----GO
----SET QUOTED_IDENTIFIER ON
----GO
ALTER PROC [DBO].[SBO_SP_TRANSACTIONNOTIFICATION] 

@OBJECT_TYPE NVARCHAR(30), 				-- SBO OBJECT TYPE
@TRANSACTION_TYPE NCHAR(1),			-- [A]DD, [U]PDATE, [D]ELETE, [C]ANCEL, C[L]OSE
@NUM_OF_COLS_IN_KEY INT,
@LIST_OF_KEY_COLS_TAB_DEL NVARCHAR(255),
@LIST_OF_COLS_VAL_TAB_DEL NVARCHAR(255)

AS

BEGIN

-- RETURN VALUES
DECLARE @ERROR  INT				-- RESULT (0 FOR NO ERROR)
DECLARE @ERROR_MESSAGE NVARCHAR (200) 		-- ERROR STRING TO BE DISPLAYED
SELECT @ERROR = 0
SELECT @ERROR_MESSAGE = N'OK'

--------------------------------------------------------------------------------------------------------------------------------

--	ADD	YOUR	CODE	HERE

--------------------ITEM MASTER DATA--------------------

---SERIES NOT MANUAL FOR SALEABLE UNITS---

IF @OBJECT_TYPE = '4' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OITM.ITEMCODE FROM OITM
WHERE 
	OITM.ITMSGRPCOD = '101'
	AND OITM.ITEMCODE NOT IN ('PRINCIPAL', 'INTEREST')
	AND OITM.SERIES <> 3 
	AND OITM.ITEMCODE=@LIST_OF_COLS_VAL_TAB_DEL)
BEGIN
	SET @ERROR= 000006
	SET @ERROR_MESSAGE='SALEABLE UNITS MUST HAVE MANUAL SERIES.'
END 

---ITEM LOT AREA IS MISSING---

IF EXISTS (SELECT OITM.ITEMCODE FROM OITM
WHERE 
	OITM.ITMSGRPCOD = '101'
	AND OITM.ITEMCODE NOT IN ('PRINCIPAL', 'INTEREST')
	AND OITM.U_AREA IS NULL 
	AND OITM.ITEMCODE=@LIST_OF_COLS_VAL_TAB_DEL)
BEGIN
	SET @ERROR= 000005
	SET @ERROR_MESSAGE='DEFINE UNIT AREA FOR THIS SALEABLE UNIT.'
END 

---ITEM LOT NO FIELD MISSING---

IF EXISTS (SELECT OITM.ITEMCODE FROM OITM
WHERE 
	OITM.ITMSGRPCOD = '101'
	AND OITM.ITEMCODE NOT IN ('PRINCIPAL', 'INTEREST')
	AND OITM.U_LOT_NO IS NULL 
	AND OITM.ITEMCODE=@LIST_OF_COLS_VAL_TAB_DEL)
BEGIN
	SET @ERROR= 000004
	SET @ERROR_MESSAGE='FILL IN LOT NO FIELD IN THE HEADER.'
END 

---ITEM BLOCK NO FIELD MISSING---

IF EXISTS (SELECT OITM.ITEMCODE FROM OITM
WHERE 
	OITM.ITMSGRPCOD = '101'
	AND OITM.ITEMCODE NOT IN ('PRINCIPAL', 'INTEREST')
	AND OITM.U_BLOCK_NO IS NULL 
	AND OITM.ITEMCODE=@LIST_OF_COLS_VAL_TAB_DEL)
BEGIN
	SET @ERROR= 000003
	SET @ERROR_MESSAGE='FILL IN BLOCK NO FIELD IN THE HEADER.'
END 

---ITEM MODEL FIELD MISSING---

IF EXISTS (SELECT OITM.ITEMCODE FROM OITM
WHERE 
	OITM.ITMSGRPCOD = '101'
	AND OITM.U_MODEL IS NULL 
	AND OITM.ITEMCODE NOT IN ('PRINCIPAL', 'INTEREST')
	AND OITM.ITEMCODE=@LIST_OF_COLS_VAL_TAB_DEL)
BEGIN
	SET @ERROR= 000002
	SET @ERROR_MESSAGE='FILL IN MODEL FIELD IN THE HEADER.'
END 

---ITEM PROJECT FIELD MISSING---

IF EXISTS (SELECT OITM.ITEMCODE FROM OITM
WHERE 
	OITM.ITMSGRPCOD = '101'
	AND OITM.U_PROJECT IS NULL 
	AND OITM.ITEMCODE NOT IN ('PRINCIPAL', 'INTEREST')
	AND OITM.ITEMCODE=@LIST_OF_COLS_VAL_TAB_DEL)
BEGIN
	SET @ERROR= 000001
	SET @ERROR_MESSAGE='FILL IN PROJECT FIELD IN THE HEADER.'
END 
END

--------------------PURCHASE REQUEST--------------------

-- REQUESTED QUANTITY OVER BUDGET AND APPROVAL IS NO---
IF @OBJECT_TYPE = '1470000113' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPRQ.DOCENTRY FROM OPRQ
INNER JOIN PRQ1 ON PRQ1.DOCENTRY = OPRQ.DOCENTRY
WHERE 
	PRQ1.FREETXT = 'TRUE'
	AND OPRQ.U_FORAPPROV <> 'Y'
	AND OPRQ.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
BEGIN
	SET @ERROR= 00110
	SET @ERROR_MESSAGE='QUANTITY REQUESTED IS OVER THE BUDGET. UPDATE FOR APPROVAL FIELD TO YES FOR PR.'
END 
END


-- PERFORM AUTOCHECK FOR APPROVAL---
	IF @OBJECT_TYPE = '1470000113' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPRQ.DOCENTRY FROM OPRQ
INNER JOIN PRQ1 ON PRQ1.DOCENTRY = OPRQ.DOCENTRY

WHERE 
			
			OPRQ.U_ACAR <> 'DONE'
			AND OPRQ.U_SUBPR_TYPE NOT IN ('DS', 'CU')
			--AND PRQ1.PROJECT <> 'EHI000'
			AND OPRQ.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00109
				SET @ERROR_MESSAGE='UPDATE AUTOCHECK FOR APPROVAL FIELD TO DONE FOR PR.'
	END 
	END




-- INCORRECT WHSE BASED ON PROJECTS---
	IF @OBJECT_TYPE = '1470000113' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPRQ.DOCENTRY FROM OPRQ
INNER JOIN PRQ1 ON PRQ1.DOCENTRY = OPRQ.DOCENTRY

WHERE 
			
			PRQ1.PROJECT LIKE 'SW%'
			AND PRQ1.WHSCODE <> 'SWRM WHS'
			AND OPRQ.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00108
				SET @ERROR_MESSAGE='INCORRECT WAREHOUSE BASED ON THE PROJECT DEFINED.'
	END 
	END




-- INCORRECT WHSE BASED ON PROJECTS---
	IF @OBJECT_TYPE = '1470000113' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPRQ.DOCENTRY FROM OPRQ
INNER JOIN PRQ1 ON PRQ1.DOCENTRY = OPRQ.DOCENTRY

WHERE 
			
			PRQ1.PROJECT LIKE 'RV%'
			AND U_PR_TYPE2 <> 'PCSC'
			AND PRQ1.WHSCODE <> 'RVRM WHS'
			AND OPRQ.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00107
				SET @ERROR_MESSAGE='INCORRECT WAREHOUSE BASED ON THE PROJECT DEFINED.'
	END 
	END



-- SALEABLE WAREHOUSE HAD DEFINED---
	IF @OBJECT_TYPE = '1470000113' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPRQ.DOCENTRY FROM OPRQ
INNER JOIN PRQ1 ON PRQ1.DOCENTRY = OPRQ.DOCENTRY

WHERE 
			PRQ1.WHSCODE  IN ( 'RVHU WHS', 'SWHU WHS')
			AND OPRQ.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00106
				SET @ERROR_MESSAGE='WAREHOUSE FOR SALEABLE ITEMS HAD DEFINED. UPDATE WAREHOUSE IN THE ROWS.'
	END 
	END




-- NO NEED FOR PURCHASE REQUEST---
	IF @OBJECT_TYPE = '1470000113' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPRQ.DOCENTRY FROM OPRQ

WHERE 
			
			OPRQ.U_SUBPR_TYPE IN ('DS', 'CU', 'SV' , 'PL')
			AND OPRQ.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00105
				SET @ERROR_MESSAGE='PURCHASE REQUEST IS NOT NEEDED FOR THIS TYPE OF TRANSACTION.'
	END 
	END

--	-- NO NEED FOR PURCHASE REQUEST---
	IF @OBJECT_TYPE = '1470000113' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPRQ.DOCENTRY FROM OPRQ

WHERE 
			OPRQ.U_PR_TYPE2 IN ('PFXA', 'OSCO', 'OSIN', 'OSIBC', 'OSLO')
			AND OPRQ.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00111
				SET @ERROR_MESSAGE='PURCHASE REQUEST IS NOT NEEDED FOR THIS TYPE OF TRANSACTION.'
	END 
	END


-- NO TAGGING OF BUDGET---
	IF @OBJECT_TYPE = '1470000113' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPRQ.DOCENTRY FROM OPRQ
INNER JOIN PRQ1 ON PRQ1.DOCENTRY = OPRQ.DOCENTRY 

WHERE 
			PRQ1.PROJECT <> 'EHI000'
			AND OPRQ.U_SUBPR_TYPE <> 'DS'
		    AND PRQ1.U_BUDGETNO IS NULL
			AND OPRQ.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR=00104
				SET @ERROR_MESSAGE='BUDGET NO IS LACKING FOR CHARGEABLE TO PROJECT RELATED TRANSACTION.'
	END 
	END



-- NO TAGGING OF DIMENSION FOR PROJECT-RELATED
	IF @OBJECT_TYPE = '1470000113' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPRQ.DOCENTRY FROM OPRQ
INNER JOIN PRQ1 ON PRQ1.DOCENTRY = OPRQ.DOCENTRY 

WHERE 
			
			PRQ1.PROJECT <> 'EHI000'
			AND OPRQ.U_SUBPR_TYPE <> 'DS'
		    AND PRQ1.U_DIMENSION1 IS NULL
			AND PRQ1.U_DIMENSION2 IS NULL
			AND PRQ1.U_DIMENSION3 IS NULL
			AND PRQ1.U_DIMENSION4 IS NULL
			AND PRQ1.U_DIMENSION5 IS NULL
			AND OPRQ.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00103
				SET @ERROR_MESSAGE='DIMENSION (S) IS LACKING FOR CHARGEABLE TO PROJECT RELATED TRANSACTION.'
	END 
	END


-- NO TAGGING OF PROJECT---
	IF @OBJECT_TYPE = '1470000113' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT PRQ1.DOCENTRY FROM PRQ1
INNER JOIN OPRQ ON PRQ1.DOCENTRY = OPRQ.DOCENTRY 

WHERE 
			
			ISNULL (PRQ1.PROJECT,'')=''
			--AND OPRQ.U_SUBPR_TYPE <> 'DS'
			--AND OPRQ.U_SUBPR_TYPE <> 'CU'
			--AND OPRQ.U_SUBPR_TYPE <> 'SV'
			--AND OPRQ.U_SUBPR_TYPE <> 'PL'
			AND PRQ1.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00102
				SET @ERROR_MESSAGE='PROJECT IS LACKING IN THE ROW. DEFINE PROJECT CODE.'
	END 
	END


-- NO TAGGING OF PURCHASE SUBCATEGORY TRANSACTION TYPE---
	IF @OBJECT_TYPE = '1470000113' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPRQ.DOCENTRY FROM OPRQ 

WHERE 
			
			OPRQ.U_PR_TYPE2 IN ( 'PLISG', 'PIMPI' , 'PLISS')
			AND OPRQ.U_SUBPR_TYPE IS NULL
			AND OPRQ.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00101
				SET @ERROR_MESSAGE='SUBCATEGORY PURCHASE TRANSACTION TYPE IS LACKING FOR THIS TRANSACTION.'
	END 
	END



-- NO TAGGING OF PURCHASE TRANSACTION TYPE---
	IF @OBJECT_TYPE = '1470000113' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPRQ.DOCENTRY FROM OPRQ 

WHERE 
			
			OPRQ.U_PR_TYPE2 IS NULL
			AND OPRQ.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00100
				SET @ERROR_MESSAGE='PURCHASE TRANSACTION TYPE IS LACKING.'
	END 
	END





---------------------------------



---PURCHASE REQUEST DRAFT---

-- REQUESTED QUANTITY OVER BUDGET AND APPROVAL IS NO---
	IF @OBJECT_TYPE = '1470000113' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF
INNER JOIN DRF1 ON DRF1.DOCENTRY = ODRF.DOCENTRY

WHERE 
			
			DRF1.FREETXT = 'TRUE'
			AND ODRF.OBJTYPE =  '1470000113'
			AND ODRF.U_FORAPPROV <> 'Y'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= -00110
				SET @ERROR_MESSAGE='QUANTITY REQUESTED IS OVER THE BUDGET. UPDATE FOR APPROVAL FIELD TO YES FOR PR.'
	END 
	END

-- PERFORM AUTOCHECK FOR APPROVAL---
	IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF
INNER JOIN DRF1 ON DRF1.DOCENTRY = ODRF.DOCENTRY

WHERE 
			
			ODRF.U_ACAR <> 'DONE'
			AND ODRF.U_SUBPR_TYPE NOT IN ('DS', 'CU')
			AND ODRF.OBJTYPE =  '1470000113'
			--AND DRF1.PROJECT <> 'EHI000'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= -00109
				SET @ERROR_MESSAGE='UPDATE AUTOCHECK FOR APPROVAL FIELD TO DONE FOR PR.'
	END 
	END


-- INCORRECT WHSE BASED ON PROJECTS---
	IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF
INNER JOIN DRF1 ON DRF1.DOCENTRY = ODRF.DOCENTRY

WHERE 
			
			DRF1.PROJECT LIKE 'SW%'
			AND DRF1.WHSCODE <> 'SWRM WHS'
			AND ODRF.OBJTYPE =  '1470000113'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= -00108
				SET @ERROR_MESSAGE='INCORRECT WAREHOUSE BASED ON THE PROJECT DEFINED.'
	END 
	END




-- INCORRECT WHSE BASED ON PROJECTS---
	IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF
INNER JOIN DRF1 ON DRF1.DOCENTRY = ODRF.DOCENTRY

WHERE 
			
			DRF1.PROJECT LIKE 'RV%'
			AND DRF1.WHSCODE <> 'RVRM WHS'
			AND U_PR_TYPE2 <> 'PCSC'
			AND ODRF.OBJTYPE =  '1470000113'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= -00108
				SET @ERROR_MESSAGE='INCORRECT WAREHOUSE BASED ON THE PROJECT DEFINED.'
	END 
	END



-- SALEABLE WAREHOUSE HAD DEFINED---
	IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF
INNER JOIN DRF1 ON DRF1.DOCENTRY = ODRF.DOCENTRY

WHERE 
			DRF1.WHSCODE  IN ( 'RVHU WHS', 'SWHU WHS')
			AND ODRF.OBJTYPE =  '1470000113'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= -00106
				SET @ERROR_MESSAGE='WAREHOUSE FOR SALEABLE ITEMS HAD DEFINED. UPDATE WAREHOUSE IN THE ROWS.'
	END 
	END



-- NO NEED FOR PURCHASE REQUEST---
	IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF

WHERE 
			ODRF.U_SUBPR_TYPE IN ('DS', 'CU', 'SV' , 'PL')
			AND ODRF.OBJTYPE =  '1470000113'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00105
				SET @ERROR_MESSAGE='PURCHASE REQUEST IS NOT NEEDED FOR THIS TYPE OF TRANSACTION.'
	END 
	END



-- NO TAGGING OF DIMENSION FOR PROJECT-RELATED
	IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF
INNER JOIN DRF1 ON DRF1.DOCENTRY = ODRF.DOCENTRY 

WHERE 
			
			DRF1.PROJECT <> 'EHI000'
		    AND DRF1.U_DIMENSION1 IS NULL
			AND DRF1.U_DIMENSION2 IS NULL
			AND DRF1.U_DIMENSION3 IS NULL
			AND DRF1.U_DIMENSION4 IS NULL
			AND DRF1.U_DIMENSION5 IS NULL
			AND ODRF.OBJTYPE =  '1470000113'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= -00103
				SET @ERROR_MESSAGE='DIMENSION (S) IS LACKING FOR CHARGEABLE TO PROJECT RELATED TRANSACTION.'
	END 
	END


-- NO TAGGING OF PROJECT---
	IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF
INNER JOIN DRF1 ON ODRF.DOCENTRY = DRF1.DOCENTRY

WHERE 
			
			ISNULL (DRF1.PROJECT,'')=''
			AND ODRF.OBJTYPE =  '1470000113'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= -00102
				SET @ERROR_MESSAGE='PROJECT IS LACKING IN THE ROW. DEFINE PROJECT CODE.'
	END 
	END


-- NO TAGGING OF PURCHASE SUBCATEGORY TRANSACTION TYPE---
	IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 

WHERE 
			
			ODRF.U_PR_TYPE2 IN ( 'PLISG', 'PIMPI' , 'PLISS')
			AND ODRF.U_SUBPR_TYPE IS NULL
			AND ODRF.OBJTYPE =  '1470000113'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= -00101
				SET @ERROR_MESSAGE='SUBCATEGORY PURCHASE TRANSACTION TYPE IS LACKING FOR THIS TRANSACTION.'
	END 
	END



-- NO TAGGING OF PURCHASE TRANSACTION TYPE---
	IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 

WHERE 
			
			ODRF.U_PR_TYPE2 IS NULL
			AND ODRF.OBJTYPE =  '1470000113'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= -00100
				SET @ERROR_MESSAGE='PURCHASE TRANSACTION TYPE IS LACKING.'
	END 
	END

---------------------------------

---PURCHASE QUOTATION


--ADDING OF PURCHASE QUOTATION WITH DUMMY SUPPLIER

		IF @OBJECT_TYPE = '540000006' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
		BEGIN

		IF EXISTS (SELECT OPQT.DOCENTRY FROM OPQT

		WHERE 
					OPQT.CARDNAME = 'DUMMY SUPPLIER'
					AND OPQT.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
					BEGIN
						SET @ERROR=00205
						SET @ERROR_MESSAGE='CANNOT ADD DUMMY SUPPLIER. UPDATE SUPPLIER CODE.'
			END 
			END



-- NO TAGGING OF BUDGET---
	IF @OBJECT_TYPE = '540000006' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPQT.DOCENTRY FROM OPQT
INNER JOIN PQT1 ON PQT1.DOCENTRY = OPQT.DOCENTRY 

WHERE 
			PQT1.PROJECT <> 'EHI000'
		    AND PQT1.U_BUDGETNO IS NULL
			AND OPQT.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR=00204
				SET @ERROR_MESSAGE='BUDGET NO IS LACKING FOR CHARGEABLE TO PROJECT RELATED TRANSACTION.'
	END 
	END



-- NO TAGGING OF DIMENSION FOR PROJECT-RELATED
	IF @OBJECT_TYPE = '540000006' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPQT.DOCENTRY FROM OPQT
INNER JOIN PQT1 ON PQT1.DOCENTRY = OPQT.DOCENTRY 

WHERE 
			
			PQT1.PROJECT <> 'EHI000'
		    AND PQT1.U_DIMENSION1 IS NULL
			AND PQT1.U_DIMENSION2 IS NULL
			AND PQT1.U_DIMENSION3 IS NULL
			AND PQT1.U_DIMENSION4 IS NULL
			AND PQT1.U_DIMENSION5 IS NULL
			AND OPQT.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00203
				SET @ERROR_MESSAGE='DIMENSION (S) IS LACKING FOR CHARGEABLE TO PROJECT RELATED TRANSACTION.'
	END 
	END


-- NO TAGGING OF PROJECT---
	IF @OBJECT_TYPE = '540000006' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT PQT1.DOCENTRY FROM PQT1

WHERE 
			
			ISNULL (PQT1.PROJECT,'')=''
			AND PQT1.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00202
				SET @ERROR_MESSAGE='PROJECT IS LACKING IN THE ROW. DEFINE PROJECT CODE.'
	END 
	END


-- NO TAGGING OF PURCHASE SUBCATEGORY TRANSACTION TYPE---
	IF @OBJECT_TYPE = '540000006' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPQT.DOCENTRY FROM OPQT 

WHERE 
			
			OPQT.U_PR_TYPE2 IN ( 'PLISG', 'PIMPI' , 'PLISS')
			AND OPQT.U_SUBPR_TYPE IS NULL
			AND OPQT.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00201
				SET @ERROR_MESSAGE='SUBCATEGORY PURCHASE TRANSACTION TYPE IS LACKING FOR THIS TRANSACTION.'
	END 
	END



-- NO TAGGING OF PURCHASE TRANSACTION TYPE---
	IF @OBJECT_TYPE = '540000006' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPQT.DOCENTRY FROM OPQT 

WHERE 
			
			OPQT.U_PR_TYPE2 IS NULL
			AND OPQT.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00200
				SET @ERROR_MESSAGE='PURCHASE TRANSACTION TYPE IS LACKING.'
	END 
	END

-- PURCHER QUOTATION IS NOT NEEDED IN SUBCATEGORY FUEL(JC)
IF @OBJECT_TYPE = '540000006' AND (@TRANSACTION_TYPE IN ('A', 'U'))
BEGIN
IF EXISTS(SELECT DOCENTRY FROM OPQT
	WHERE 
	U_SUBPR_TYPE = 'FL'
	AND DOCENTRY = @LIST_OF_COLS_VAL_TAB_DEL)

BEGIN
	SET @ERROR = 00206
	SET @ERROR_MESSAGE = 'PURCHASE QUOTATION IS NOT NEEDED IN THIS SUBCATEGORY PURCHASE TRANSACTION TYPE'
END
END


---------------------------


---PURCHASE QUOTATION DRAFT


--ADDING OF PURCHASE QUOTATION WITH DUMMY SUPPLIER

		IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
		BEGIN

		IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF

		WHERE 
					ODRF.CARDNAME = 'DUMMY SUPPLIER'
					AND ODRF.OBJTYPE =  '540000006'
					AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
					BEGIN
						SET @ERROR=-00205
						SET @ERROR_MESSAGE='CANNOT ADD DUMMY SUPPLIER. UPDATE SUPPLIER CODE.'
			END 
			END



-- NO TAGGING OF BUDGET---
	IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF
INNER JOIN DRF1 ON DRF1.DOCENTRY = ODRF.DOCENTRY 

WHERE 
			DRF1.PROJECT <> 'EHI000'
		    AND DRF1.U_BUDGETNO IS NULL
			AND ODRF.OBJTYPE =  '540000006'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR=-00204
				SET @ERROR_MESSAGE='BUDGET NO IS LACKING FOR CHARGEABLE TO PROJECT RELATED TRANSACTION.'
	END 
	END



-- NO TAGGING OF DIMENSION FOR PROJECT-RELATED
	IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF
INNER JOIN DRF1 ON DRF1.DOCENTRY = ODRF.DOCENTRY 

WHERE 
			
			DRF1.PROJECT <> 'EHI000'
		    AND DRF1.U_DIMENSION1 IS NULL
			AND DRF1.U_DIMENSION2 IS NULL
			AND DRF1.U_DIMENSION3 IS NULL
			AND DRF1.U_DIMENSION4 IS NULL
			AND DRF1.U_DIMENSION5 IS NULL
			AND ODRF.OBJTYPE =  '540000006'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= -00203
				SET @ERROR_MESSAGE='DIMENSION (S) IS LACKING FOR CHARGEABLE TO PROJECT RELATED TRANSACTION.'
	END 
	END


-- NO TAGGING OF PROJECT---
	IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT DRF1.DOCENTRY FROM DRF1
INNER JOIN ODRF ON DRF1.DOCENTRY = ODRF.DOCENTRY

WHERE 
			
			ISNULL (DRF1.PROJECT,'')=''
			AND ODRF.OBJTYPE =  '540000006'
			AND DRF1.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= -00202
				SET @ERROR_MESSAGE='PROJECT IS LACKING IN THE ROW. DEFINE PROJECT CODE.'
	END 
	END


-- NO TAGGING OF PURCHASE SUBCATEGORY TRANSACTION TYPE---
	IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 

WHERE 
			
			ODRF.U_PR_TYPE2 IN ( 'PLISG', 'PIMPI' , 'PLISS')
			AND ODRF.U_SUBPR_TYPE IS NULL
			AND ODRF.OBJTYPE =  '540000006'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= -00201
				SET @ERROR_MESSAGE='SUBCATEGORY PURCHASE TRANSACTION TYPE IS LACKING FOR THIS TRANSACTION.'
	END 
	END



-- NO TAGGING OF PURCHASE TRANSACTION TYPE---
	IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 

WHERE 
			
			ODRF.U_PR_TYPE2 IS NULL
			AND ODRF.OBJTYPE =  '540000006'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= -00200
				SET @ERROR_MESSAGE='PURCHASE TRANSACTION TYPE IS LACKING.'
	END 
	END

-- PURCHER QUOTATION IS NOT NEEDED IN SUBCATEGORY FUEL(JC)
IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U'))
BEGIN
IF EXISTS(SELECT DOCENTRY FROM ODRF
	WHERE 
	U_SUBPR_TYPE = 'FL'
	AND ODRF.OBJTYPE =  '540000006'
	AND DOCENTRY = @LIST_OF_COLS_VAL_TAB_DEL)

BEGIN
	SET @ERROR = 00206
	SET @ERROR_MESSAGE = 'PURCHASE QUOTATION IS NOT NEEDED IN THIS SUBCATEGORY PURCHASE TRANSACTION TYPE'
END
END


---------------------------------

---PURCHASE ORDER---

---- PURCHASE REQUEST IS REQUIRED IN SUCATEGORY FUEL (JC)
--IF @OBJECT_TYPE = '22' AND (@TRANSACTION_TYPE IN ('A', 'U'))
--BEGIN
--IF EXISTS(SELECT OPOR.DOCENTRY FROM POR1 
--	INNER JOIN OPOR ON OPOR.DOCENTRY = POR1.DOCENTRY
--	WHERE
--	POR1.BASETYPE = -1
--	AND OPOR.U_SUBPR_TYPE = 'FL'
--	AND OPOR.DOCENTRY = @LIST_OF_COLS_VAL_TAB_DEL)

--BEGIN
--	SET @ERROR = 00220
--	SET @ERROR_MESSAGE = 'PURCHASE REQUIEST IS NEEDED IN THIS SUBCATEGORY PURCHASE TRANSACTION TYPE'
--END
--END


-- ORDERED TOTAL OVER BUDGET AND APPROVAL IS NO---
	IF @OBJECT_TYPE = '22' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPOR.DOCENTRY FROM OPOR
INNER JOIN POR1 ON POR1.DOCENTRY = OPOR.DOCENTRY

WHERE 
			
			POR1.FREETXT = 'TRUE'
			AND OPOR.U_FORAPPROV <> 'P'
			AND OPOR.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00219
				SET @ERROR_MESSAGE='TOTAL AMOUNT ORDERED IS OVER THE BUDGET. UPDATE FOR APPROVAL FIELD TO YES FOR PO.'
	END 
	END


-- PERFORM AUTOCHECK FOR APPROVAL---
	IF @OBJECT_TYPE = '22' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPOR.DOCENTRY FROM OPOR
INNER JOIN POR1 ON POR1.DOCENTRY = OPOR.DOCENTRY

WHERE 
			
			OPOR.U_ACAR <> 'PO'
			AND OPOR.U_SUBPR_TYPE NOT IN ('DS', 'CU')
			AND POR1.PROJECT <> 'EHI000'
			AND OPOR.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00218
				SET @ERROR_MESSAGE='UPDATE AUTOCHECK FOR APPROVAL FIELD TO DONE FOR PO.'
	END 
	END






--DOCUMENT TOTAL HIGHER THAN TOTAL COMMISSION IN SALES ORDER--

		IF @OBJECT_TYPE = '22' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
		BEGIN

		IF EXISTS (SELECT OPOR.DOCENTRY FROM OPOR
		LEFT JOIN ORDR ON OPOR.U_SONO1 = ORDR.DOCENTRY

		WHERE 
					OPOR.U_PR_TYPE2 ='OSCO'
					AND OPOR.U_SONO1 = ORDR.DOCENTRY
					AND OPOR.DOCTOTAL > ORDR.U_TOTCOM
					AND OPOR.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
					BEGIN
						SET @ERROR= 00217
						SET @ERROR_MESSAGE='DOCUMENT TOTAL HIGHER THAN TOTAL COMMISSION IN SALES ORDER'
			END 
			END




-- SO NUMBER IS REQUIRED FOR COMMISSION--

		IF @OBJECT_TYPE = '22' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
		BEGIN

		IF EXISTS (SELECT OPOR.DOCENTRY FROM OPOR
		WHERE 
					OPOR.U_PR_TYPE2 ='OSCO'
					AND OPOR.U_SONO1 IS NULL
					AND OPOR.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
	BEGIN
						SET @ERROR= 00216
						SET @ERROR_MESSAGE='TAG THE RELATED SALES ORDER FOR THIS TRANSACTION'
			END 
			END



--- PURCHASE QUOTATION IS REQUIRED

		IF @OBJECT_TYPE = '22' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
		BEGIN

			IF EXISTS (SELECT OPOR.DOCENTRY FROM OPOR 
		LEFT JOIN POR1 ON POR1.DOCENTRY = OPOR.DOCENTRY

		WHERE POR1.BASETYPE IN ( -1, 1470000113)
		AND OPOR.U_PR_TYPE2 = 'PFXA'
		AND OPOR.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL) 

		BEGIN 

		SET @ERROR=  00215

		SET @ERROR_MESSAGE = 'BASED PURCHASE QUOTATION IS REQUIRED IN ADDING THIS TRANSACTION.' 

		END 

		END 

--- PURCHASE REQUEST AND PURCHASE QUOTATION ARE REQUIRED

			IF @OBJECT_TYPE = '22'  AND (@TRANSACTION_TYPE IN ('A', 'U')) 
		BEGIN

			IF EXISTS (SELECT OPOR.DOCENTRY FROM OPOR 
		LEFT JOIN POR1 ON POR1.DOCENTRY = OPOR.DOCENTRY

		WHERE POR1.BASETYPE IN ( -1, 1470000113)
		AND OPOR.U_SUBPR_TYPE IN ('CM', 'CS', 'EQ')
		AND OPOR.OBJTYPE =  '22'
		AND OPOR.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL) 

		BEGIN 

		SET @ERROR=  -00315

		SET @ERROR_MESSAGE = 'BASE PURCHASE REQUEST AND PURCHASE QUOTATION ARE REQUIRED IN ADDING THIS TRANSACTION.' 

		END 

		END 

--- PURCHASE REQUEST AND PURCHASE QUOTATION ARE REQUIRED

			IF @OBJECT_TYPE = '22'  AND (@TRANSACTION_TYPE IN ('A', 'U')) 
		BEGIN

			IF EXISTS (SELECT OPOR.DOCENTRY FROM OPOR 
		LEFT JOIN POR1 ON POR1.DOCENTRY = OPOR.DOCENTRY

		WHERE POR1.BASETYPE IN ( -1, 1470000113)
		AND OPOR.U_PR_TYPE2 = 'PCSC'
		AND OPOR.OBJTYPE =  '22'
		AND OPOR.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL) 

		BEGIN 

		SET @ERROR=  -00420

		SET @ERROR_MESSAGE = 'BASE PURCHASE REQUEST AND PURCHASE QUOTATION ARE REQUIRED IN ADDING THIS TRANSACTION.' 

		END

		END

---ADDING OF DUMMY SUPPLIER--

		IF @OBJECT_TYPE = '22' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
		BEGIN

		IF EXISTS (SELECT OPOR.DOCENTRY FROM OPOR

		WHERE 
					OPOR.CARDNAME = 'DUMMY SUPPLIER'
					AND OPOR.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
					BEGIN
						SET @ERROR=  00214
						SET @ERROR_MESSAGE='CANNOT ADD DUMMY SUPPLIER. UPDATE SUPPLIER CODE.'
			END 
			END


--TRANSACTION TYPE INCONSISTENT IN PURCHASE REQUEST--



IF @OBJECT_TYPE = '22' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT OPOR.DOCENTRY FROM OPOR 
			INNER JOIN POR1 ON OPOR.DOCENTRY = POR1.DOCENTRY
			INNER JOIN PRQ1  ON PRQ1.DOCENTRY = POR1.BASEENTRY 
			INNER JOIN OPRQ ON OPRQ.DOCENTRY= PRQ1.DOCENTRY AND POR1.BASETYPE=OPRQ.OBJTYPE 

			WHERE 
			OPRQ.U_PR_TYPE2 <> OPOR.U_PR_TYPE2
			AND OPOR.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR = 00213
				SET @ERROR_MESSAGE='TRANSACTION TYPE INCONSISTENT IN PURCHASE REQUEST.'

		END
		END
		
--PROJECT CODE INCONSISTENT IN PURCHASE REQUEST--

IF @OBJECT_TYPE = '22' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT OPOR.DOCENTRY FROM OPOR 
			INNER JOIN POR1 ON OPOR.DOCENTRY = POR1.DOCENTRY
			INNER JOIN PRQ1  ON PRQ1.DOCENTRY = POR1.BASEENTRY 
			INNER JOIN OPRQ ON OPRQ.DOCENTRY= PRQ1.DOCENTRY AND POR1.BASETYPE=OPRQ.OBJTYPE 

			WHERE 
			PRQ1.PROJECT <> POR1.PROJECT
			AND OPOR.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR= 00212
				SET @ERROR_MESSAGE= 'PROJECT CODE INCONSISTENT IN PURCHASE REQUEST.'

		END
		END

--BUDGET NO. INCONSISTENT IN PURCHASE REQUEST--

IF @OBJECT_TYPE = '22' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT OPOR.DOCENTRY FROM OPOR 
			INNER JOIN POR1 ON OPOR.DOCENTRY = POR1.DOCENTRY
			INNER JOIN PRQ1  ON PRQ1.DOCENTRY = POR1.BASEENTRY 
			INNER JOIN OPRQ ON OPRQ.DOCENTRY= PRQ1.DOCENTRY AND POR1.BASETYPE=OPRQ.OBJTYPE 

			WHERE 
			PRQ1.U_BUDGETNO <> POR1.U_BUDGETNO
			AND OPOR.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR= 00211
				SET @ERROR_MESSAGE= 'BUDGET NO. INCONSISTENT IN PURCHASE REQUEST.'

		END
		END

--TRANSACTION TYPE INCONSISTENT WITH BASED PURCHASE QUOTATION--

IF @OBJECT_TYPE = '22' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT OPOR.DOCENTRY FROM OPOR 
			INNER JOIN POR1 ON OPOR.DOCENTRY = POR1.DOCENTRY
			INNER JOIN PQT1  ON PQT1.DOCENTRY = POR1.BASEENTRY AND POR1.BASETYPE = 540000006
			INNER JOIN OPQT ON OPQT.DOCENTRY = PQT1.DOCENTRY


			WHERE 
			OPQT.U_PR_TYPE2 <> OPOR.U_PR_TYPE2
			AND OPOR.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR= 00210
				SET @ERROR_MESSAGE='TRANSACTION TYPE INCONSISTENT WITH BASED PURCHASE QUOTATION.'

		END
		END



--TRANSACTION TYPE INCONSISTENT WITH BASED PURCHASE REQUEST--

IF @OBJECT_TYPE = '22' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT OPOR.DOCENTRY FROM OPOR 
			INNER JOIN POR1 ON OPOR.DOCENTRY = POR1.DOCENTRY
			INNER JOIN PRQ1  ON PRQ1.DOCENTRY = POR1.BASEENTRY AND POR1.BASETYPE = 1470000113
			INNER JOIN OPRQ ON OPRQ.DOCENTRY = PRQ1.DOCENTRY


			WHERE 
			OPRQ.U_PR_TYPE2 <> OPOR.U_PR_TYPE2
			AND OPOR.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR= 00209
				SET @ERROR_MESSAGE='TRANSACTION TYPE INCONSISTENT WITH BASED PURCHASE REQUEST.'

		END
		END

--PROJECT CODE INCONSISTENT WITH BASED PURCHASE QUOTATION--

IF @OBJECT_TYPE = '22' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT OPOR.DOCENTRY FROM OPOR 
			INNER JOIN POR1 ON OPOR.DOCENTRY = POR1.DOCENTRY
			INNER JOIN PQT1  ON PQT1.DOCENTRY = POR1.BASEENTRY AND POR1.BASETYPE = 540000006

			WHERE 
			PQT1.PROJECT <> POR1.PROJECT
			AND OPOR.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR = 00208
				SET @ERROR_MESSAGE= 'PROJECT CODE INCONSISTENT WITH THE BASED PURCHASE QUOTATION.'

		END
		END


--PROJECT CODE INCONSISTENT WITH THE BASED PURCHASE REQUEST--

IF @OBJECT_TYPE = '22' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT OPOR.DOCENTRY FROM OPOR 
			INNER JOIN POR1 ON OPOR.DOCENTRY = POR1.DOCENTRY
			LEFT JOIN PRQ1 ON PRQ1.DOCENTRY = POR1.BASEENTRY AND POR1.BASETYPE = 1470000113

			WHERE 
			PRQ1.PROJECT <> POR1.PROJECT
			AND OPOR.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR= 00207
				SET @ERROR_MESSAGE= 'PROJECT CODE INCONSISTENT WITH THE BASED PURCHASE REQUEST.'

		END
		END



--BUDGET NO. INCONSISTENT IN PURCHASE QUOTATION--

IF @OBJECT_TYPE = '22' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT OPOR.DOCENTRY FROM OPOR 
			INNER JOIN POR1 ON OPOR.DOCENTRY = POR1.DOCENTRY
			INNER JOIN PQT1  ON PQT1.DOCENTRY = POR1.BASEENTRY AND POR1.BASETYPE = 540000006


			WHERE 
			PQT1.U_BUDGETNO <> POR1.U_BUDGETNO
			AND OPOR.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR= 00206
				SET @ERROR_MESSAGE= 'BUDGET NO. INCONSISTENT WITH THE BASED PURCHASE QUOTATION.'

		END
		END


--BUDGET NO. INCONSISTENT IN PURCHASE REQUEST--

IF @OBJECT_TYPE = '22' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT OPOR.DOCENTRY FROM OPOR 
			INNER JOIN POR1 ON OPOR.DOCENTRY = POR1.DOCENTRY
			LEFT JOIN PRQ1 ON PRQ1.DOCENTRY = POR1.BASEENTRY AND POR1.BASETYPE = 1470000113
		

			WHERE 
			PRQ1.U_BUDGETNO <> POR1.U_BUDGETNO
			AND OPOR.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR= 00205
				SET @ERROR_MESSAGE= 'BUDGET NO. INCONSISTENT WITH THE BASED PURCHASE REQUEST.'

		END
		END



-- NO TAGGING OF BUDGET---
	IF @OBJECT_TYPE = '22' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPOR.DOCENTRY FROM OPOR
INNER JOIN POR1 ON POR1.DOCENTRY = OPOR.DOCENTRY 

WHERE 
			POR1.PROJECT <> 'EHI000'
		    AND POR1.U_BUDGETNO IS NULL
			AND OPOR.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR=00204
				SET @ERROR_MESSAGE='BUDGET NO IS LACKING FOR CHARGEABLE TO PROJECT RELATED TRANSACTION.'
	END 
	END



-- NO TAGGING OF DIMENSION FOR PROJECT-RELATED
	IF @OBJECT_TYPE = '22' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPOR.DOCENTRY FROM OPOR
INNER JOIN POR1 ON POR1.DOCENTRY = OPOR.DOCENTRY 

WHERE 
			
			POR1.PROJECT <> 'EHI000'
		    AND POR1.U_DIMENSION1 IS NULL
			AND POR1.U_DIMENSION2 IS NULL
			AND POR1.U_DIMENSION3 IS NULL
			AND POR1.U_DIMENSION4 IS NULL
			AND POR1.U_DIMENSION5 IS NULL
			AND OPOR.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00203
				SET @ERROR_MESSAGE='DIMENSION (S) IS LACKING FOR CHARGEABLE TO PROJECT RELATED TRANSACTION.'
	END 
	END


-- NO TAGGING OF PROJECT---
	IF @OBJECT_TYPE = '22' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT POR1.DOCENTRY FROM POR1

WHERE 
			
			ISNULL (POR1.PROJECT,'')=''
			AND POR1.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00202
				SET @ERROR_MESSAGE='PROJECT IS LACKING IN THE ROW. DEFINE PROJECT CODE.'
	END 
	END



-- NO TAGGING OF PURCHASE SUBCATEGORY TRANSACTION TYPE---
	IF @OBJECT_TYPE = '22' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPOR.DOCENTRY FROM OPOR 

WHERE 
			
			OPOR.U_PR_TYPE2 IN ( 'PLISG', 'PIMPI' , 'PLISS')
			AND OPOR.U_SUBPR_TYPE IS NULL
			AND OPOR.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00601
				SET @ERROR_MESSAGE='SUBCATEGORY PURCHASE TRANSACTION TYPE IS LACKING FOR THIS TRANSACTION.'
	END 
	END




-- NO TAGGING OF PURCHASE TRANSACTION TYPE---
	IF @OBJECT_TYPE = '22' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPOR.DOCENTRY FROM OPOR 

WHERE 
			
			OPOR.U_PR_TYPE2 IS NULL
			AND OPOR.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00201
				SET @ERROR_MESSAGE='PURCHASE TRANSACTION TYPE IS LACKING.'
	END 
	END




----
---PURCHASE ORDER DRAFT

-- PURCHASE REQUEST IS REQUIRED IN SUCATEGORY FUEL (JC)
IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U'))
BEGIN
IF EXISTS(SELECT ODRF.DOCENTRY FROM ODRF 
	INNER JOIN DRF1 ON ODRF.DOCENTRY = DRF1.DOCENTRY
	WHERE
	ODRF.OBJTYPE =  '22'
	AND DRF1.BASETYPE = -1
	AND ODRF.U_SUBPR_TYPE = 'FL'
	AND ODRF.DOCENTRY = @LIST_OF_COLS_VAL_TAB_DEL)

BEGIN
	SET @ERROR = 00220
	SET @ERROR_MESSAGE = 'PURCHASE REQUIEST IS NEEDED IN THIS SUBCATEGORY PURCHASE TRANSACTION TYPE'
END
END

-- REQUESTED QUANTITY OVER BUDGET AND APPROVAL IS NO---
	IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF
INNER JOIN DRF1 ON DRF1.DOCENTRY = ODRF.DOCENTRY

WHERE 
			
			DRF1.FREETXT = 'TRUE'
			AND ODRF.U_FORAPPROV <> 'P'
			AND ODRF.OBJTYPE =  '22'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00219
				SET @ERROR_MESSAGE='TOTAL AMOUNT ORDERED IS OVER THE BUDGET. UPDATE FOR APPROVAL FIELD TO YES FOR PO.'
	END 
	END


-- PERFORM AUTOCHECK FOR APPROVAL---
	IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF
INNER JOIN DRF1 ON DRF1.DOCENTRY = ODRF.DOCENTRY

WHERE 
			
			ODRF.U_ACAR <> 'PO'
			AND ODRF.U_SUBPR_TYPE NOT IN ('DS', 'CU')
			AND DRF1.PROJECT <> 'EHI000'
			AND ODRF.OBJTYPE =  '22'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= -00218
				SET @ERROR_MESSAGE='UPDATE AUTOCHECK FOR APPROVAL FIELD TO DONE FOR PO.'
	END 
	END


--DOCUMENT TOTAL HIGHER THAN TOTAL COMMISSION IN SALES ORDER--

		IF @OBJECT_TYPE = '112'  AND (@TRANSACTION_TYPE IN ('A', 'U')) 
		BEGIN

		IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF
		LEFT JOIN ORDR ON ODRF.U_SONO1 = ORDR.DOCENTRY

		WHERE 
					ODRF.U_PR_TYPE2 ='OSCO'
					AND ODRF.U_SONO1 = ORDR.DOCENTRY
					AND ODRF.DOCTOTAL > ORDR.U_TOTCOM
					AND ODRF.OBJTYPE =  '22'
					AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
					BEGIN
						SET @ERROR= -00217
						SET @ERROR_MESSAGE='DOCUMENT TOTAL HIGHER THAN TOTAL COMMISSION IN SALES ORDER'
			END 
			END




-- SO NUMBER IS REQUIRED FOR COMMISSION--

		IF @OBJECT_TYPE = '112'  AND (@TRANSACTION_TYPE IN ('A', 'U')) 
		BEGIN

		IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF
		WHERE 
					ODRF.U_PR_TYPE2 ='OSCO'
					AND ODRF.U_SONO1 IS NULL
						AND ODRF.OBJTYPE =  '22'
					AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
	BEGIN
						SET @ERROR= -00216
						SET @ERROR_MESSAGE='TAG THE RELATED SALES ORDER FOR THIS TRANSACTION'
			END 
			END


----- PURCHASE REQUEST AND PURCHASE QUOTATION ARE REQUIRED

			IF @OBJECT_TYPE = '112'  AND (@TRANSACTION_TYPE IN ('A', 'U')) 
		BEGIN

			IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 
		LEFT JOIN DRF1 ON DRF1.DOCENTRY = ODRF.DOCENTRY

		WHERE DRF1.BASETYPE IN ( -1, 1470000113)
		AND ODRF.U_SUBPR_TYPE IN ('CM', 'CS', 'EQ')
		--OR ODRF.U_PR_TYPE2 = 'PCSC'
		AND ODRF.OBJTYPE =  '22'
		AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL) 

		BEGIN 

		SET @ERROR=  -00515

		SET @ERROR_MESSAGE = 'BASE PURCHASE REQUEST AND PURCHASE QUOTATION ARE REQUIRED IN ADDING THIS TRANSACTION.' 

		END 

		END 



---ADDING OF DUMMY SUPPLIER--

		IF @OBJECT_TYPE = '112'  AND (@TRANSACTION_TYPE IN ('A', 'U'))  
		BEGIN

		IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF

		WHERE 
					ODRF.CARDNAME = 'DUMMY SUPPLIER'
					AND ODRF.OBJTYPE =  '22'
					AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
					BEGIN
						SET @ERROR=  -00214
						SET @ERROR_MESSAGE='CANNOT ADD DUMMY SUPPLIER. UPDATE SUPPLIER CODE.'
			END 
			END


--TRANSACTION TYPE INCONSISTENT IN PURCHASE REQUEST--



IF @OBJECT_TYPE = '112'  AND (@TRANSACTION_TYPE IN ('A', 'U'))  
BEGIN

			IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 
			INNER JOIN DRF1 ON ODRF.DOCENTRY = DRF1.DOCENTRY
			INNER JOIN PRQ1  ON PRQ1.DOCENTRY = DRF1.BASEENTRY 
			INNER JOIN OPRQ ON OPRQ.DOCENTRY= PRQ1.DOCENTRY AND DRF1.BASETYPE=OPRQ.OBJTYPE 

			WHERE 
			OPRQ.U_PR_TYPE2 <> ODRF.U_PR_TYPE2
			AND ODRF.OBJTYPE =  '22'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR = -00213
				SET @ERROR_MESSAGE='TRANSACTION TYPE INCONSISTENT IN PURCHASE REQUEST.'

		END
		END
		
--PROJECT CODE INCONSISTENT IN PURCHASE REQUEST--

IF @OBJECT_TYPE = '112'  AND (@TRANSACTION_TYPE IN ('A', 'U'))  
BEGIN

			IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 
			INNER JOIN DRF1 ON ODRF.DOCENTRY = DRF1.DOCENTRY
			INNER JOIN PRQ1  ON PRQ1.DOCENTRY = DRF1.BASEENTRY 
			INNER JOIN OPRQ ON OPRQ.DOCENTRY= PRQ1.DOCENTRY AND DRF1.BASETYPE=OPRQ.OBJTYPE 

			WHERE 
			PRQ1.PROJECT <> DRF1.PROJECT
			AND ODRF.OBJTYPE =  '22'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR= -00212
				SET @ERROR_MESSAGE= 'PROJECT CODE INCONSISTENT IN PURCHASE REQUEST.'

		END
		END

--BUDGET NO. INCONSISTENT IN PURCHASE REQUEST--

IF @OBJECT_TYPE = '112'  AND (@TRANSACTION_TYPE IN ('A', 'U'))  
BEGIN

			IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 
			INNER JOIN DRF1 ON ODRF.DOCENTRY = DRF1.DOCENTRY
			INNER JOIN PRQ1  ON PRQ1.DOCENTRY = DRF1.BASEENTRY 
			INNER JOIN OPRQ ON OPRQ.DOCENTRY= PRQ1.DOCENTRY AND DRF1.BASETYPE=OPRQ.OBJTYPE 

			WHERE 
			PRQ1.U_BUDGETNO <> DRF1.U_BUDGETNO
			AND ODRF.OBJTYPE =  '22'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR= -00211
				SET @ERROR_MESSAGE= 'BUDGET NO. INCONSISTENT IN PURCHASE REQUEST.'

		END
		END

--TRANSACTION TYPE INCONSISTENT WITH BASED PURCHASE QUOTATION--
IF @OBJECT_TYPE = '112'  AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 
			INNER JOIN DRF1 ON ODRF.DOCENTRY = DRF1.DOCENTRY
			INNER JOIN PQT1  ON PQT1.DOCENTRY = DRF1.BASEENTRY AND DRF1.BASETYPE = 540000006
			INNER JOIN OPQT ON OPQT.DOCENTRY = PQT1.DOCENTRY


			WHERE 
			OPQT.U_PR_TYPE2 <> ODRF.U_PR_TYPE2
			AND ODRF.OBJTYPE =  '22'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR= -00210
				SET @ERROR_MESSAGE='TRANSACTION TYPE INCONSISTENT WITH BASED PURCHASE QUOTATION.'

		END
		END



--TRANSACTION TYPE INCONSISTENT WITH BASED PURCHASE REQUEST--

IF @OBJECT_TYPE = '112'  AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 
			INNER JOIN DRF1 ON ODRF.DOCENTRY = DRF1.DOCENTRY
			INNER JOIN PRQ1  ON PRQ1.DOCENTRY = DRF1.BASEENTRY AND DRF1.BASETYPE = 1470000113
			INNER JOIN OPRQ ON OPRQ.DOCENTRY = PRQ1.DOCENTRY


			WHERE 
			OPRQ.U_PR_TYPE2 <> ODRF.U_PR_TYPE2
			AND ODRF.OBJTYPE =  '22'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR= -00209
				SET @ERROR_MESSAGE='TRANSACTION TYPE INCONSISTENT WITH BASED PURCHASE REQUEST.'

		END
		END

--PROJECT CODE INCONSISTENT WITH BASED PURCHASE QUOTATION--

IF @OBJECT_TYPE = '112'  AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 
			INNER JOIN DRF1 ON ODRF.DOCENTRY = DRF1.DOCENTRY
			INNER JOIN PQT1  ON PQT1.DOCENTRY = DRF1.BASEENTRY AND DRF1.BASETYPE = 540000006

			WHERE 
			PQT1.PROJECT <> DRF1.PROJECT
			AND ODRF.OBJTYPE =  '22'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR = -00208
				SET @ERROR_MESSAGE= 'PROJECT CODE INCONSISTENT WITH THE BASED PURCHASE QUOTATION.'

		END
		END


--PROJECT CODE INCONSISTENT WITH THE BASED PURCHASE REQUEST--

IF @OBJECT_TYPE = '112'  AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 
			INNER JOIN DRF1 ON ODRF.DOCENTRY = DRF1.DOCENTRY
			LEFT JOIN PRQ1 ON PRQ1.DOCENTRY = DRF1.BASEENTRY AND DRF1.BASETYPE = 1470000113

			WHERE 
			PRQ1.PROJECT <> DRF1.PROJECT
			AND ODRF.OBJTYPE =  '22'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR= -00207
				SET @ERROR_MESSAGE= 'PROJECT CODE INCONSISTENT WITH THE BASED PURCHASE REQUEST.'

		END
		END



--BUDGET NO. INCONSISTENT IN PURCHASE QUOTATION--

IF @OBJECT_TYPE = '112'  AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 
			INNER JOIN DRF1 ON ODRF.DOCENTRY = DRF1.DOCENTRY
			INNER JOIN PQT1  ON PQT1.DOCENTRY = DRF1.BASEENTRY AND DRF1.BASETYPE = 540000006


			WHERE 
			PQT1.U_BUDGETNO <> DRF1.U_BUDGETNO
			AND ODRF.OBJTYPE =  '22'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR= -00206
				SET @ERROR_MESSAGE= 'BUDGET NO. INCONSISTENT WITH THE BASED PURCHASE QUOTATION.'

		END
		END


--BUDGET NO. INCONSISTENT IN PURCHASE REQUEST--


IF @OBJECT_TYPE = '112'  AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 
			INNER JOIN DRF1 ON ODRF.DOCENTRY = DRF1.DOCENTRY
			LEFT JOIN PRQ1 ON PRQ1.DOCENTRY = DRF1.BASEENTRY AND DRF1.BASETYPE = 1470000113
		

			WHERE 
			PRQ1.U_BUDGETNO <> DRF1.U_BUDGETNO
			AND ODRF.OBJTYPE =  '22'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR= -00205
				SET @ERROR_MESSAGE= 'BUDGET NO. INCONSISTENT WITH THE BASED PURCHASE REQUEST.'

		END
		END



-- NO TAGGING OF BUDGET---
	IF @OBJECT_TYPE = '112'  AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF
INNER JOIN DRF1 ON DRF1.DOCENTRY = ODRF.DOCENTRY 

WHERE 
			DRF1.PROJECT <> 'EHI000'
		    AND DRF1.U_BUDGETNO IS NULL
			AND ODRF.OBJTYPE =  '22'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR=-00204
				SET @ERROR_MESSAGE='BUDGET NO IS LACKING FOR CHARGEABLE TO PROJECT RELATED TRANSACTION.'
	END 
	END



-- NO TAGGING OF DIMENSION FOR PROJECT-RELATED
		IF @OBJECT_TYPE = '112'  AND (@TRANSACTION_TYPE IN ('A', 'U'))
BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF
INNER JOIN DRF1 ON DRF1.DOCENTRY = ODRF.DOCENTRY 

WHERE 
			
			DRF1.PROJECT <> 'EHI000'
		    AND DRF1.U_DIMENSION1 IS NULL
			AND DRF1.U_DIMENSION2 IS NULL
			AND DRF1.U_DIMENSION3 IS NULL
			AND DRF1.U_DIMENSION4 IS NULL
			AND DRF1.U_DIMENSION5 IS NULL
			AND ODRF.OBJTYPE =  '22'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= -00203
				SET @ERROR_MESSAGE='DIMENSION (S) IS LACKING FOR CHARGEABLE TO PROJECT RELATED TRANSACTION.'
	END 
	END


-- NO TAGGING OF PROJECT---
	IF @OBJECT_TYPE = '112'  AND (@TRANSACTION_TYPE IN ('A', 'U'))
BEGIN

IF EXISTS (SELECT DRF1.DOCENTRY FROM DRF1


WHERE 
			
			ISNULL (DRF1.PROJECT,'')=''
			AND DRF1.OBJTYPE = '22'
			AND DRF1.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= -00202
				SET @ERROR_MESSAGE='PROJECT IS LACKING IN THE ROW. DEFINE PROJECT CODE.'
	END 
	END


-- NO TAGGING OF PURCHASE SUBCATEGORY TRANSACTION TYPE---
	IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 

WHERE 
			
			ODRF.U_PR_TYPE2 IN ( 'PLISG', 'PIMPI' , 'PLISS')
			AND ODRF.U_SUBPR_TYPE IS NULL
			AND ODRF.OBJTYPE =  '22'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00201
				SET @ERROR_MESSAGE='SUBCATEGORY PURCHASE TRANSACTION TYPE IS LACKING FOR THIS TRANSACTION.'
	END 
	END



-- NO TAGGING OF PURCHASE TRANSACTION TYPE---
	IF @OBJECT_TYPE = '112'  AND (@TRANSACTION_TYPE IN ('A', 'U'))
BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 

WHERE 
			
			ODRF.U_PR_TYPE2 IS NULL
			AND ODRF.OBJTYPE =  '22'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= -00200
				SET @ERROR_MESSAGE='PURCHASE TRANSACTION TYPE IS LACKING.'
	END 
	END


-----------------------------------







---A/P DOWN PAYMENT INVOICE



-- NO TAGGING OF BUDGET---
	IF @OBJECT_TYPE = '204' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODPO.DOCENTRY FROM ODPO
INNER JOIN DPO1 ON DPO1.DOCENTRY = ODPO.DOCENTRY 

WHERE 
			DPO1.PROJECT <> 'EHI000'
		    AND DPO1.U_BUDGETNO IS NULL
			AND ODPO.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR=00304
				SET @ERROR_MESSAGE='BUDGET NO IS LACKING FOR CHARGEABLE TO PROJECT RELATED TRANSACTION.'
	END 
	END



-- NO TAGGING OF DIMENSION FOR PROJECT-RELATED
	IF @OBJECT_TYPE = '204' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODPO.DOCENTRY FROM ODPO
INNER JOIN DPO1 ON DPO1.DOCENTRY = ODPO.DOCENTRY 

WHERE 
			
			DPO1.PROJECT <> 'EHI000'
		    AND DPO1.U_DIMENSION1 IS NULL
			AND DPO1.U_DIMENSION2 IS NULL
			AND DPO1.U_DIMENSION3 IS NULL
			AND DPO1.U_DIMENSION4 IS NULL
			AND DPO1.U_DIMENSION5 IS NULL
			AND ODPO.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00303
				SET @ERROR_MESSAGE='DIMENSION (S) IS LACKING FOR CHARGEABLE TO PROJECT RELATED TRANSACTION.'
	END 
	END


-- NO TAGGING OF PROJECT---
	IF @OBJECT_TYPE = '204' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT DPO1.DOCENTRY FROM DPO1

WHERE 
			
			ISNULL (DPO1.PROJECT,'')=''
			AND DPO1.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00302
				SET @ERROR_MESSAGE='PROJECT IS LACKING IN THE ROW. DEFINE PROJECT CODE.'
	END 
	END


-- NO TAGGING OF PURCHASE TRANSACTION TYPE---
	IF @OBJECT_TYPE = '204' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODPO.DOCENTRY FROM ODPO 

WHERE 
			
			ODPO.U_PR_TYPE2 IS NULL
			AND ODPO.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00301
				SET @ERROR_MESSAGE='PURCHASE TRANSACTION TYPE IS LACKING.'
	END 
	END



---AP DOWN PAYMENT DRAFT


-- NO TAGGING OF BUDGET---
	IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF
INNER JOIN DRF1 ON DRF1.DOCENTRY = ODRF.DOCENTRY 

WHERE 
			DRF1.PROJECT <> 'EHI000'
		    AND DRF1.U_BUDGETNO IS NULL
			AND ODRF.OBJTYPE =  '204'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= -00304
				SET @ERROR_MESSAGE='BUDGET NO IS LACKING FOR CHARGEABLE TO PROJECT RELATED TRANSACTION.'
	END 
	END



-- NO TAGGING OF DIMENSION FOR PROJECT-RELATED
	IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF
INNER JOIN DRF1 ON DRF1.DOCENTRY = ODRF.DOCENTRY 

WHERE 
			
			DRF1.PROJECT <> 'EHI000'
		    AND DRF1.U_DIMENSION1 IS NULL
			AND DRF1.U_DIMENSION2 IS NULL
			AND DRF1.U_DIMENSION3 IS NULL
			AND DRF1.U_DIMENSION4 IS NULL
			AND DRF1.U_DIMENSION5 IS NULL
			AND ODRF.OBJTYPE =  '204'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= -00303
				SET @ERROR_MESSAGE='DIMENSION (S) IS LACKING FOR CHARGEABLE TO PROJECT RELATED TRANSACTION.'
	END 
	END


-- NO TAGGING OF PROJECT---
	IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT DRF1.DOCENTRY FROM DRF1

WHERE 
			
			ISNULL (DRF1.PROJECT,'')=''
			AND DRF1.OBJTYPE =  '204'
			AND DRF1.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00302
				SET @ERROR_MESSAGE='PROJECT IS LACKING IN THE ROW. DEFINE PROJECT CODE.'
	END 
	END




-- NO TAGGING OF PURCHASE TRANSACTION TYPE---
	IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 

WHERE 
			
			ODRF.U_PR_TYPE2 IS NULL
			AND ODRF.OBJTYPE =  '204'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= -00301
				SET @ERROR_MESSAGE='PURCHASE TRANSACTION TYPE IS LACKING.'
	END 
	END


--------------------------------------------


---GOODS RECEIPT PO

--- PLATE NO. IS LACKING
IF @OBJECT_TYPE = '20' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPDN.DOCENTRY FROM OPDN

WHERE 
			OPDN.U_VEHICLE_PN IS NULL
			AND OPDN.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00507
				SET @ERROR_MESSAGE='INPUT VEHICLE PLATE NO.'
	END 
	END



--- DRIVER'S NAME IS LACKING
IF @OBJECT_TYPE = '20' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPDN.DOCENTRY FROM OPDN

WHERE 
			OPDN.U_DRIVER_NAME IS NULL
			AND OPDN.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00506
				SET @ERROR_MESSAGE='INPUT DRIVER NAME'
	END 
	END



--- VENDOR REFERENCE NUMBER IS LACKING
IF @OBJECT_TYPE = '20' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPDN.DOCENTRY FROM OPDN

WHERE 
			ISNULL (OPDN.NUMATCARD, '') = ''
			AND OPDN.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00505
				SET @ERROR_MESSAGE='INPUT VENDOR REFERENCE NUMBER.'
	END 
	END

-- NO TAGGING OF BUDGET---
	IF @OBJECT_TYPE = '20' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPDN.DOCENTRY FROM OPDN
INNER JOIN PDN1 ON PDN1.DOCENTRY = OPDN.DOCENTRY 

WHERE 
			PDN1.PROJECT <> 'EHI000'
		    AND PDN1.U_BUDGETNO IS NULL
			AND OPDN.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR=00504
				SET @ERROR_MESSAGE='BUDGET NO IS LACKING FOR CHARGEABLE TO PROJECT RELATED TRANSACTION.'
	END 
	END



-- NO TAGGING OF DIMENSION FOR PROJECT-RELATED
	IF @OBJECT_TYPE = '20' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPDN.DOCENTRY FROM OPDN
INNER JOIN PDN1 ON PDN1.DOCENTRY = OPDN.DOCENTRY 

WHERE 
			
			PDN1.PROJECT <> 'EHI000'
		    AND PDN1.U_DIMENSION1 IS NULL
			AND PDN1.U_DIMENSION2 IS NULL
			AND PDN1.U_DIMENSION3 IS NULL
			AND PDN1.U_DIMENSION4 IS NULL
			AND PDN1.U_DIMENSION5 IS NULL
			AND OPDN.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00503
				SET @ERROR_MESSAGE='DIMENSION (S) IS LACKING FOR CHARGEABLE TO PROJECT RELATED TRANSACTION.'
	END 
	END


-- NO TAGGING OF PROJECT---
	IF @OBJECT_TYPE = '20' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT PDN1.DOCENTRY FROM PDN1

WHERE 
			
			ISNULL (PDN1.PROJECT,'')=''
			AND PDN1.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00502
				SET @ERROR_MESSAGE='PROJECT IS LACKING IN THE ROW. DEFINE PROJECT CODE.'
	END 
	END


-- NO TAGGING OF PURCHASE TRANSACTION TYPE---
	IF @OBJECT_TYPE = '20' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPDN.DOCENTRY FROM OPDN 

WHERE 
			
			OPDN.U_PR_TYPE2 IS NULL
			AND OPDN.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00401
				SET @ERROR_MESSAGE='PURCHASE TRANSACTION TYPE IS LACKING.'
	END 
	END

--NO BASE PO
IF @OBJECT_TYPE = '20' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT OPDN.DOCENTRY FROM OPDN 
			INNER JOIN PDN1 ON OPDN.DOCENTRY = PDN1.DOCENTRY

			WHERE 
			PDN1.BASETYPE = -1
			AND OPDN.DOCTYPE = 'I'
			AND OPDN.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR=01112
				SET @ERROR_MESSAGE='BASE PO IS REQUIRED FOR THIS TRANSACTION.' 

		END
		END



---------------------------------------------


---GOODS RETURN


---REASON FOR RETURN IN THE ROWS
IF @OBJECT_TYPE = '21' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT RPD1.DOCENTRY FROM RPD1

WHERE 
			RPD1.RETURNRSN = -1
			AND RPD1.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00503
				SET @ERROR_MESSAGE='ENTER REASON FOR RETURN IN THE ROWS.'
	END 
	END


---REASON FOR RETURN IN THE HEADER
IF @OBJECT_TYPE = '21' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ORPD.DOCENTRY FROM ORPD

WHERE 
			ORPD.U_RETRES IS NULL 
			AND ORPD.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00502
				SET @ERROR_MESSAGE='ENTER REASON FOR RETURN IN THE HEADER.'
	END 
	END


-- NO TAGGING OF PURCHASE TRANSACTION TYPE---
	IF @OBJECT_TYPE = '21' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ORPD.DOCENTRY FROM ORPD 

WHERE 
			
			ORPD.U_PR_TYPE2 IS NULL
			AND ORPD.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00501
				SET @ERROR_MESSAGE='PURCHASE TRANSACTION TYPE IS LACKING.'
	END 
	END



---------------------------------------
-----AP INVOICE DRAFT

-- NO TAGGING OF PURCHASE TRANSACTION TYPE---
	IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 

WHERE 
			
			ODRF.U_PR_TYPE2 IS NULL
			AND ODRF.OBJTYPE =  '18'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00700
				SET @ERROR_MESSAGE='PURCHASE TRANSACTION TYPE IS LACKING.'
	END 
	END

-- NO TAGGING OF PURCHASE SUBCATEGORY TRANSACTION TYPE---
	IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 

WHERE 
			
			ODRF.U_PR_TYPE2 IN ( 'PLISG', 'PIMPI' , 'PLISS')
			AND ODRF.OBJTYPE =  '18'
			AND ODRF.U_SUBPR_TYPE IS NULL
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00701
				SET @ERROR_MESSAGE='SUBCATEGORY PURCHASE TRANSACTION TYPE IS LACKING FOR THIS TRANSACTION.'
	END 
	END

-- NO TAGGING OF PROJECT---
	IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF

WHERE 
			
			ISNULL (ODRF.PROJECT,'')=''
			AND ODRF.OBJTYPE =  '18'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00400
				SET @ERROR_MESSAGE='PROJECT IS LACKING. DEFINE PROJECT CODE.'
	END 
	END

---LACKING PERCENTAGE OF COMPLETION
IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 
			INNER JOIN DRF1 ON ODRF.DOCENTRY = DRF1.DOCENTRY
			

			WHERE 
			ODRF.U_PR_TYPE2 = 'PCSC'
			AND ODRF.OBJTYPE =  '18'
			AND DRF1.U_CTPC IS NULL
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR=00411
				SET @ERROR_MESSAGE='INPUT CURRENT PERCENTAGE OF COMPLETION FOR THIS CONTRACTED SERVICES IN ROW.'

		END
		END

--UPDATE G/L CODE TO SUBCON CHARGES-

IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 
			INNER JOIN DRF1 ON ODRF.DOCENTRY = DRF1.DOCENTRY

			WHERE 
			ODRF.U_PR_TYPE2 = 'PLISS'
			AND ODRF.OBJTYPE =  '18'
			AND DRF1.ACCTCODE <> 'OC390000'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR=002111
				SET @ERROR_MESSAGE='UPDATE G/L CODE TO SUBCON CHARGES FOR THIS TRANSACTION'

		END
		END

--UPDATE G/L CODE TO SUBCON CHARGES-

IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 
			INNER JOIN DRF1 ON ODRF.DOCENTRY = DRF1.DOCENTRY

			WHERE 
			ODRF.U_PR_TYPE2 = 'PLISS'
			AND ODRF.OBJTYPE =  '18'
			AND DRF1.ACCTCODE <> 'OC390000'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR=00511
				SET @ERROR_MESSAGE='UPDATE G/L CODE TO SUBCON CHARGES FOR THIS TRANSACTION'

		END
		END

---- NO BASE PURCHASE REQUEST AND PURCHASE QUOTATION
--IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
--BEGIN

--			IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 
--			INNER JOIN DRF1 ON ODRF.DOCENTRY = DRF1.DOCENTRY

--			WHERE 
--			DRF1.BASETYPE = -1
--			AND ODRF.U_PR_TYPE2 = 'PCSC'
--			OR ODRF.U_SUBPR_TYPE IN ('CM', 'CS', 'EQ')
--			AND ODRF.OBJTYPE =  '18'
--			AND DRF1.ACCTCODE <> 'OC390000'
--			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

--			BEGIN
--				SET @ERROR=01111
--				SET @ERROR_MESSAGE='BASE PURCHASE REQUEST AND PURCHASE QUOTATION ARE REQUIRED FOR THIS TRANSACTION.'

--		END
--		END

---- NO BASE PURCHASE QUOTATION
--IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
--BEGIN

--			IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 
--			INNER JOIN DRF1 ON ODRF.DOCENTRY = DRF1.DOCENTRY

--			WHERE 
--			DRF1.BASETYPE = 1470000113
--			AND ODRF.U_PR_TYPE2 = 'PCSC'
--			OR ODRF.U_SUBPR_TYPE IN ('CM', 'CS', 'EQ')
--			AND ODRF.OBJTYPE =  '18'
--			AND DRF1.ACCTCODE <> 'OC390000'
--			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

--			BEGIN
--				SET @ERROR=01111
--				SET @ERROR_MESSAGE='BASE PURCHASE QUOTATION IS REQUIRED FOR THIS TRANSACTION.'

--		END
--		END

----NO BASE PURCHASE QUOTATION
--IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
--BEGIN

--			IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 
--			INNER JOIN DRF1 ON ODRF.DOCENTRY = DRF1.DOCENTRY

--			WHERE 
--			DRF1.BASETYPE = -1
--			OR DRF1.BASETYPE <> 540000006
--			AND ODRF.U_PR_TYPE2 = 'PFXA'
--			OR ODRF.U_SUBPR_TYPE IN ('DS', 'CU', 'SV')
--			AND ODRF.OBJTYPE =  '18'
--			AND DRF1.ACCTCODE <> 'OC390000'
--			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

--			BEGIN
--				SET @ERROR=01113
--				SET @ERROR_MESSAGE='BASE PURCHASE QUOTATION IS REQUIRED FOR THIS TRANSACTION.'

--		END
--		END

		--NO BASE GRPO
IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 
			INNER JOIN DRF1 ON ODRF.DOCENTRY = DRF1.DOCENTRY

			WHERE 
			DRF1.BASETYPE = -1
			AND ODRF.DOCTYPE = 'I'
			AND ODRF.OBJTYPE =  '18'
			AND DRF1.ACCTCODE <> 'OC390000'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR=01112
				SET @ERROR_MESSAGE='BASE GOODS RECEIPT PO IS REQUIRED FOR THIS TRANSACTION.' 

		END
		END

--OVER BILLING

IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN			
	IF EXISTS (SELECT DISTINCT 
		--'TRUE',
		--		PO.ITEM,
		--		PO.POTOTAL,
		AP.ITEMCODE
		--AP.PERCENTCOM,
		--ISNULL(AP.APTOTAL,0) AS PO,
		--ISNULL((PO.POTOTAL * AP.PERCENTCOM),0) AS MAXIM
		FROM 			
		-- AP DETAILS
				(SELECT 
					A.U_CTPC AS PERCENTCOM,
					A.ITEMCODE,
					A.DOCENTRY,
					A.BASEREF [PODOCENTRY]
					FROM DRF1 A
					LEFT JOIN ODRF B ON B.DOCENTRY = A.DOCENTRY
					WHERE B.CANCELED = 'N' AND A.ITEMCODE LIKE 'RU%'
					AND A.OBJTYPE =  '18'
					GROUP BY A.ITEMCODE, A.U_CTPC, A.DOCENTRY , A.BASEREF
				) AS AP			
				LEFT JOIN
		--TO GET DETAILS OF THE BUDGET BASED ON PER ITEMCODE AND BUDGET NUMBER. EXCEPT FOR UNAPPROVED AND CANCELED BUDGET--
				(SELECT 
					SUM(ISNULL(A.LINETOTAL,0)) AS POTOTAL,
					A.ITEMCODE AS ITEM,
					A.DOCENTRY AS PODOCENTRY	
					FROM POR1 A
					LEFT JOIN OPOR B ON A.DOCENTRY = B.DOCENTRY
					WHERE B.CANCELED = 'N' AND A.ITEMCODE LIKE 'RU%'
					GROUP BY A.ITEMCODE, A.DOCENTRY 
				) AS PO ON AP.ITEMCODE = PO.ITEM AND PO.PODOCENTRY = AP.PODOCENTRY
				LEFT JOIN DRF1 ON DRF1.DOCENTRY = AP.DOCENTRY 
				WHERE ISNULL((SELECT SUM(ISNULL(P.LINETOTAL,0)) FROM DRF1 P WHERE P.BASEREF = AP.PODOCENTRY AND P.BASETYPE = 22),0) > ((PO.POTOTAL) * (AP.PERCENTCOM/100))
				AND AP.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR=00413
				SET @ERROR_MESSAGE='OVER BILLING.'
			END
		END



---AP INVOICE---

--ADDING OF DUMMY SUPPLIER--

		IF @OBJECT_TYPE = '18' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
		BEGIN

		IF EXISTS (SELECT OPCH.DOCENTRY FROM OPCH

		WHERE 
					OPCH.CARDNAME = 'DUMMY SUPPLIER'
					AND OPCH.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
					BEGIN
						SET @ERROR= 00417
						SET @ERROR_MESSAGE='CANNOT ADD DUMMY SUPPLIER. UPDATE SUPPLIER CODE.'
			END 
			END


---OVERBILLING

---OVERBILLING

IF @OBJECT_TYPE = '18' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN			
	IF EXISTS (SELECT DISTINCT 
		--'TRUE',
		--		PO.ITEM,
		--		PO.POTOTAL,
		AP.ITEMCODE
		--AP.PERCENTCOM,
		--ISNULL(AP.APTOTAL,0) AS PO,
		--ISNULL((PO.POTOTAL * AP.PERCENTCOM),0) AS MAXIM
		FROM 			
		-- AP DETAILS
				(SELECT 
					A.U_CTPC AS PERCENTCOM,
					A.ITEMCODE,
					A.DOCENTRY,
					C.DOCENTRY [PODOCENTRY]
					FROM PCH1 A
					LEFT JOIN OPCH B ON B.DOCENTRY = A.DOCENTRY
					LEFT JOIN POR1 C ON C.DOCENTRY = A.BASEENTRY AND A.BASETYPE = 22
					WHERE B.CANCELED = 'N' AND A.ITEMCODE LIKE 'RU%'
					GROUP BY A.ITEMCODE, A.U_CTPC, A.DOCENTRY , C.DOCENTRY
				) AS AP			
				LEFT JOIN
		--TO GET DETAILS OF THE BUDGET BASED ON PER ITEMCODE AND BUDGET NUMBER. EXCEPT FOR UNAPPROVED AND CANCELED BUDGET--
				(SELECT 
					SUM(ISNULL(A.LINETOTAL,0)) AS POTOTAL,
					A.ITEMCODE AS ITEM,
					A.DOCENTRY AS PODOCENTRY	
					FROM POR1 A
					LEFT JOIN OPOR B ON A.DOCENTRY = B.DOCENTRY
					WHERE B.CANCELED = 'N' AND A.ITEMCODE LIKE 'RU%'
					GROUP BY A.ITEMCODE, A.DOCENTRY 
				) AS PO ON AP.ITEMCODE = PO.ITEM AND PO.PODOCENTRY = AP.PODOCENTRY
				LEFT JOIN PCH1 ON PCH1.DOCENTRY = AP.DOCENTRY 
				WHERE ISNULL((SELECT SUM(ISNULL(P.LINETOTAL,0)) FROM PCH1 P WHERE P.BASEREF = AP.PODOCENTRY AND P.BASETYPE = 22),0) > ((PO.POTOTAL) * (AP.PERCENTCOM/100))
				AND PCH1.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR=00413
				SET @ERROR_MESSAGE='OVER BILLING.'
			END
		END

		


-----LACKING PERCENTAGE OF COMPLETION (ERROR)
----IF @OBJECT_TYPE = '18' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
----BEGIN

----			IF EXISTS (SELECT OPCH.DOCENTRY FROM OPCH 
----			INNER JOIN PCH1 ON OPCH.DOCENTRY = PCH1.DOCENTRY
----			LEFT JOIN POR1 ON POR1.DOCENTRY = PCH1.BASEENTRY AND PCH1.BASETYPE = 22
			

----			WHERE 
----			OPCH.U_PR_TYPE2 = 'PCSC'
----			AND PCH1.ITEMCODE = POR1.ITEMCODE
----			AND PCH1.U_BUDGETNO = POR1.U_BUDGETNO
----			AND	((SELECT SUM(PCH1.GTOTAL) FROM PCH1 
----			INNER JOIN OPCH ON OPCH.DOCENTRY = PCH1.DOCENTRY WHERE OPCH.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL GROUP BY PCH1.ITEMCODE
----			)) > POR1.GTOTAL
----			AND PCH1.GTOTAL >= POR1.GTOTAL
		

----			AND OPCH.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
	

----			BEGIN
----				SET @ERROR=00411
----				SET @ERROR_MESSAGE='INPUT PERCENTAGE OF COMPLETION IN THE ROWS'

----		END
----		END


---LACKING PERCENTAGE OF COMPLETION
IF @OBJECT_TYPE = '18' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT OPCH.DOCENTRY FROM OPCH 
			INNER JOIN PCH1 ON OPCH.DOCENTRY = PCH1.DOCENTRY
			

			WHERE 
			OPCH.U_PR_TYPE2 = 'PCSC'
			AND PCH1.U_CTPC IS NULL
			AND OPCH.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR=00411
				SET @ERROR_MESSAGE='INPUT CURRENT PERCENTAGE OF COMPLETION FOR THIS CONTRACTED SERVICES IN ROW.'

		END
		END





--UPDATE G/L CODE TO SUBCON CHARGES-

IF @OBJECT_TYPE = '18' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT OPCH.DOCENTRY FROM OPCH 
			INNER JOIN PCH1 ON OPCH.DOCENTRY = PCH1.DOCENTRY

			WHERE 
			OPCH.U_PR_TYPE2 = 'PLISS'
			AND PCH1.ACCTCODE <> 'OC390000'
			AND OPCH.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR=00411
				SET @ERROR_MESSAGE='UPDATE G/L CODE TO SUBCON CHARGES FOR THIS TRANSACTION'

		END
		END



--BUDGET NO INCONSISTENT IN PURCHASE ORDER (WITH GRPO)

IF @OBJECT_TYPE = '18' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT OPCH.DOCENTRY FROM OPCH 
			INNER JOIN PCH1 ON OPCH.DOCENTRY = PCH1.DOCENTRY
			LEFT JOIN PDN1 ON PDN1.DOCENTRY = PCH1.BASEENTRY	
			LEFT JOIN POR1 ON POR1.DOCENTRY = PDN1.BASEENTRY

			WHERE 
			POR1.U_BUDGETNO <> PCH1.U_BUDGETNO
			AND OPCH.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR=00611
				SET @ERROR_MESSAGE= 'BUDGET NO. INCONSISTENT IN PURCHASE ORDER.'

		END
		END


--BUDGET NO. INCONSISTENT IN PURCHASE ORDER (NO GRPO)

IF @OBJECT_TYPE = '18' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT OPCH.DOCENTRY FROM OPCH 
			INNER JOIN PCH1 ON OPCH.DOCENTRY = PCH1.DOCENTRY
			INNER JOIN POR1  ON POR1.DOCENTRY = PCH1.BASEENTRY 
			INNER JOIN OPOR ON OPOR.DOCENTRY= POR1.DOCENTRY AND PCH1.BASETYPE=OPOR.OBJTYPE 

			WHERE 
			POR1.U_BUDGETNO <>  PCH1.U_BUDGETNO
			AND OPCH.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR=00610
				SET @ERROR_MESSAGE= 'BUDGET NO. INCONSISTENT IN PURCHASE ORDER.'

		END
		END





--PROJECT CODE INCONSISTENT IN PURCHASE ORDER (WITH GRPO)

IF @OBJECT_TYPE = '18' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT OPCH.DOCENTRY FROM OPCH 
			INNER JOIN PCH1 ON OPCH.DOCENTRY = PCH1.DOCENTRY
			LEFT JOIN PDN1 ON PDN1.DOCENTRY = PCH1.BASEENTRY	
			LEFT JOIN POR1 ON POR1.DOCENTRY = PDN1.BASEENTRY

			WHERE 
			POR1.PROJECT <> PCH1.PROJECT
			AND OPCH.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR=00609
				SET @ERROR_MESSAGE= 'PROJECT CODE INCONSISTENT IN PURCHASE ORDER.'

		END
		END


--PROJECT CODE INCONSISTENT IN PURCHASE ORDER (NO GRPO)

IF @OBJECT_TYPE = '18' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT OPCH.DOCENTRY FROM OPCH 
			INNER JOIN PCH1 ON OPCH.DOCENTRY = PCH1.DOCENTRY
			INNER JOIN POR1  ON POR1.DOCENTRY = PCH1.BASEENTRY 
			INNER JOIN OPOR ON OPOR.DOCENTRY= POR1.DOCENTRY AND PCH1.BASETYPE=OPOR.OBJTYPE 

			WHERE 
			POR1.PROJECT <> PCH1.PROJECT
			AND OPCH.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR=00608
				SET @ERROR_MESSAGE= 'PROJECT CODE INCONSISTENT IN PURCHASE ORDER.'

		END
		END




--TRANSACTION TYPE INCONSISTENT IN PURCHASE ORDER (WITH GRPO)

IF @OBJECT_TYPE = '18' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT OPCH.DOCENTRY FROM OPCH 
			INNER JOIN PCH1 ON OPCH.DOCENTRY = PCH1.DOCENTRY
			LEFT JOIN PDN1 ON PDN1.DOCENTRY = PCH1.BASEENTRY	
			LEFT JOIN POR1 ON POR1.DOCENTRY = PDN1.BASEENTRY
			INNER JOIN OPOR ON POR1.DOCENTRY = OPOR.DOCENTRY

			WHERE 
			OPCH.U_PR_TYPE2 <> OPOR.U_PR_TYPE2
			AND OPCH.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR=00607
				SET @ERROR_MESSAGE= 'PURCHASE TRANSACTION TYPE INCONSISTENT IN PURCHASE ORDER.'

		END
		END


--- TRANSACTION TYPE INCONSISTENT WITH THE PURCHASE ORDER (NO GRPO)

IF @OBJECT_TYPE = '18' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

			IF EXISTS (SELECT OPCH.DOCENTRY FROM OPCH 
			INNER JOIN PCH1 ON OPCH.DOCENTRY = PCH1.DOCENTRY
			INNER JOIN POR1  ON POR1.DOCENTRY = PCH1.BASEENTRY 
			INNER JOIN OPOR ON OPOR.DOCENTRY= POR1.DOCENTRY AND PCH1.BASETYPE=OPOR.OBJTYPE 

			WHERE 
			OPCH.U_PR_TYPE2 <> OPOR.U_PR_TYPE2
			AND OPCH.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR=00606
				SET @ERROR_MESSAGE= 'PURCHASE TRANSACTION TYPE INCONSISTENT IN PURCHASE ORDER.'

		END
		END




-- NO BASED GRPO
IF @OBJECT_TYPE = '18' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPCH.DOCENTRY FROM OPCH
INNER JOIN PCH1 ON PCH1.DOCENTRY = OPCH.DOCENTRY 

WHERE 
			PCH1.BASETYPE = -1
			--OR PCH1.BASETYPE <> 22
			AND OPCH.DOCTYPE = 'I'
			AND OPCH.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR=00605
				SET @ERROR_MESSAGE='BASE GOODS RECEIPT PO IS REQUIRED FOR THIS TRANSACTION.'
	END 
	END





-- NO TAGGING OF BUDGET---
	IF @OBJECT_TYPE = '18' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPCH.DOCENTRY FROM OPCH
INNER JOIN PCH1 ON PCH1.DOCENTRY = OPCH.DOCENTRY 

WHERE 
			PCH1.PROJECT <> 'EHI000'
		    AND PCH1.U_BUDGETNO IS NULL
			AND OPCH.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR=00604
				SET @ERROR_MESSAGE='BUDGET NO IS LACKING FOR CHARGEABLE TO PROJECT RELATED TRANSACTION.'
	END 
	END



-- NO TAGGING OF DIMENSION FOR PROJECT-RELATED
	IF @OBJECT_TYPE = '18' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPCH.DOCENTRY FROM OPCH
INNER JOIN PCH1 ON PCH1.DOCENTRY = OPCH.DOCENTRY 

WHERE 
			
			PCH1.PROJECT <> 'EHI000'
		    AND PCH1.U_DIMENSION1 IS NULL
			AND PCH1.U_DIMENSION2 IS NULL
			AND PCH1.U_DIMENSION3 IS NULL
			AND PCH1.U_DIMENSION4 IS NULL
			AND PCH1.U_DIMENSION5 IS NULL
			AND OPCH.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00603
				SET @ERROR_MESSAGE='DIMENSION (S) IS LACKING FOR CHARGEABLE TO PROJECT RELATED TRANSACTION.'
	END 
	END


-- NO TAGGING OF PROJECT---
	IF @OBJECT_TYPE = '18' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT PCH1.DOCENTRY FROM PCH1

WHERE 
			
			ISNULL (PCH1.PROJECT,'')=''
			AND PCH1.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00602
				SET @ERROR_MESSAGE='PROJECT IS LACKING IN THE ROW. DEFINE PROJECT CODE.'
	END 
	END

-- NO TAGGING OF PURCHASE SUBCATEGORY TRANSACTION TYPE---
	IF @OBJECT_TYPE = '18' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPCH.DOCENTRY FROM OPCH 

WHERE 
			
			OPCH.U_PR_TYPE2 IN ( 'PLISG', 'PIMPI' , 'PLISS')
			AND OPCH.U_SUBPR_TYPE IS NULL
			AND OPCH.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00601
				SET @ERROR_MESSAGE='SUBCATEGORY PURCHASE TRANSACTION TYPE IS LACKING FOR THIS TRANSACTION.'
	END 
	END



-- NO TAGGING OF PURCHASE TRANSACTION TYPE---
	IF @OBJECT_TYPE = '18' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPCH.DOCENTRY FROM OPCH 

WHERE 
			
			OPCH.U_PR_TYPE2 IS NULL
			AND OPCH.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00600
				SET @ERROR_MESSAGE='PURCHASE TRANSACTION TYPE IS LACKING.'
	END 
	END

---- NO BASE PURCHASE REQUEST AND PURCHASE QUOTATION
IF @OBJECT_TYPE = '18' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPCH.DOCENTRY FROM OPCH
INNER JOIN PCH1 ON PCH1.DOCENTRY = OPCH.DOCENTRY 

WHERE 
			PCH1.BASETYPE = -1
			AND OPCH.U_PR_TYPE2 = 'PCSC'
			AND OPCH.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR=00906
				SET @ERROR_MESSAGE='BASE PURCHASE REQUEST AND PURCHASE QUOTATION ARE REQUIRED FOR THIS TRANSACTION.'
	END 
	END

---- NO BASE PURCHASE REQUEST AND PURCHASE QUOTATION
IF @OBJECT_TYPE = '18' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPCH.DOCENTRY FROM OPCH
INNER JOIN PCH1 ON PCH1.DOCENTRY = OPCH.DOCENTRY 

WHERE 
			PCH1.BASETYPE = -1
			AND OPCH.U_SUBPR_TYPE IN ('CM', 'CS', 'EQ')
			AND OPCH.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR=00907
				SET @ERROR_MESSAGE='BASE PURCHASE REQUEST AND PURCHASE QUOTATION ARE REQUIRED FOR THIS TRANSACTION.'
	END 
	END


-- NO BASE PURCHASE QUOTATION
IF @OBJECT_TYPE = '18' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OPCH.DOCENTRY FROM OPCH
INNER JOIN PCH1 ON PCH1.DOCENTRY = OPCH.DOCENTRY 

WHERE 
			PCH1.BASETYPE = -1
			--AND OPCH.U_PR_TYPE2 IN ('PFXA')
			AND OPCH.U_SUBPR_TYPE IN ('DS', 'CU', 'SV')
			AND OPCH.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR=00908
				SET @ERROR_MESSAGE='BASE PURCHASE QUOTATION IS REQUIRED FOR THIS TRANSACTION.'
	END 
	END











---AP CM---

---- REASON FOR RETURN-----------------------
	IF @OBJECT_TYPE = '19' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ORPC.DOCENTRY FROM ORPC

WHERE 
			
			ORPC.U_RETRES IS NULL
			AND ORPC.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00407
				SET @ERROR_MESSAGE='ENTER REASON FOR RETURN.'
	END 
	END

---GOODS ISSUE DRAFT

--SUBCON/BP CODE---

IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 

BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 

WHERE 
			ODRF.U_ISSUETYPE IN ('DS', 'ICS')
			AND ODRF.U_CODE IS NULL
			AND ODRF.OBJTYPE =  '60'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00408
				SET @ERROR_MESSAGE='FILL IN SUBCON/BP CODE FIELD.'
	END 
	END

--FILL IN PROJECT IN ROWS---

IF @OBJECT_TYPE = '112' AND (@TRANSACTION_TYPE IN ('A', 'U')) 

BEGIN

IF EXISTS (SELECT ODRF.DOCENTRY FROM ODRF 
INNER JOIN DRF1 ON DRF1.DOCENTRY = ODRF.DOCENTRY

WHERE 
			ODRF.U_ISSUETYPE IN ('DS', 'ICS')
			AND DRF1.PROJECT IS NULL
			AND ODRF.OBJTYPE =  '60'
			AND ODRF.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00408
				SET @ERROR_MESSAGE='FILL IN PROJECT IN ROWS.'
	END 
	END

---GOODS ISSUE

--LACKING ISSUANCE TYPE

IF @OBJECT_TYPE = '60' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OIGE.DOCENTRY FROM OIGE

WHERE 
			
			OIGE.U_ISSUETYPE IS NULL
			AND OIGE.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00308
				SET @ERROR_MESSAGE='LACKING ISSUANCE TYPE.'
	END 
	END

--SUBCON/BP CODE---

IF @OBJECT_TYPE = '60' AND (@TRANSACTION_TYPE IN ('A', 'U')) 

BEGIN

IF EXISTS (SELECT OIGE.DOCENTRY FROM OIGE 

WHERE 
			OIGE.U_ISSUETYPE IN ('DS', 'ICS')
			AND OIGE.U_CODE IS NULL
			AND OIGE.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00408
				SET @ERROR_MESSAGE='FILL IN SUBCON/BP CODE FIELD.'
	END 
	END

--ISSUANCE EXCEEDS BUDGETED QUANTITY

IF @OBJECT_TYPE = '60' AND (@TRANSACTION_TYPE IN ('A', 'U')) 

BEGIN

IF EXISTS (SELECT OIGE.DOCENTRY FROM OIGE 
INNER JOIN IGE1 ON IGE1.DOCENTRY = OIGE.DOCENTRY 

WHERE 
			IGE1.U_TQUANTITY = 'TRUE'
			AND OIGE.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00508
				SET @ERROR_MESSAGE='ISSUANCE EXCEEDS BUDGETED QUANTITY.'
	END 
	END

---LACKING PROJECT IN ROWS

IF @OBJECT_TYPE = '60' AND (@TRANSACTION_TYPE IN ('A', 'U')) 

BEGIN

IF EXISTS (SELECT OIGE.DOCENTRY FROM OIGE 
INNER JOIN IGE1 ON IGE1.DOCENTRY = OIGE.DOCENTRY 

WHERE 
			ISNULL (IGE1.PROJECT,'')=''
			AND OIGE.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00608
				SET @ERROR_MESSAGE='FILL IN PROJECT IN ROWS.'
	END 
	END

---RETIREMENT---

--PROJECT---

IF @OBJECT_TYPE = 'RETIREMENT' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ORTI.DOCENTRY FROM ORTI
INNER JOIN RTI1 ON RTI1.DOCENTRY = ORTI.DOCENTRY

WHERE 
			
			ORTI.DOCTYPE IN ('SCRAPPING')
			AND RTI1.PROJECT IS NULL
			AND ORTI.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00409
				SET @ERROR_MESSAGE='FILL IN PROJECT FIELD.'
	END 
	END


---AR INVOICE---

IF @OBJECT_TYPE = '13' AND (@TRANSACTION_TYPE IN ('A', 'U')) 

BEGIN
			IF EXISTS (SELECT OINV.DOCENTRY FROM OINV
			INNER JOIN INV1 ON OINV.DOCENTRY = INV1.DOCENTRY
			INNER JOIN DPI1 ON DPI1.DOCENTRY = INV1.DOCENTRY
			INNER JOIN RDR1  ON DPI1.DOCENTRY = RDR1.BASEENTRY 
			INNER JOIN ORDR ON ORDR.DOCENTRY = RDR1.DOCENTRY

			WHERE 
			ORDR.DOCSTATUS = 'C'
			AND OINV.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR=00411
				SET @ERROR_MESSAGE='INVALID AR DOWN PAYMENT INVOICE APPILED FROM CANCELLED SALES ORDER.'

		END
		END

---ISSUE FOR PRODUCTION

---RCM REFERENCE MISSING

IF @OBJECT_TYPE = '60' AND (@TRANSACTION_TYPE IN ('A', 'U')) 

BEGIN
			IF EXISTS (SELECT OIGE.DOCENTRY FROM OIGE
			INNER JOIN IGE1 ON OIGE.DOCENTRY = IGE1.DOCENTRY
			

			WHERE 
			OIGE.U_RMC IS NULL
			AND IGE1.ITEMCODE LIKE 'RM%'
			AND OIGE.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR=00418
				SET @ERROR_MESSAGE='READY MIXED CONCRETE REFERENCE IS MISSING.'

		END
		END

---CPP REFERENCE MISSING

IF @OBJECT_TYPE = '60' AND (@TRANSACTION_TYPE IN ('A', 'U')) 

BEGIN
			IF EXISTS (SELECT OIGE.DOCENTRY FROM OIGE
			INNER JOIN IGE1 ON OIGE.DOCENTRY = IGE1.DOCENTRY
			

			WHERE 
			OIGE.U_CPP IS NULL
			AND IGE1.ITEMCODE LIKE 'RM%'
			AND OIGE.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)

			BEGIN
				SET @ERROR=00415
				SET @ERROR_MESSAGE='CONCRETE POURING PERMIT REFERENCE IS MISSING .'

		END
		END



---OUTGOING PAYMENT---(JC)


IF @OBJECT_TYPE = '46' AND (@TRANSACTION_TYPE='A' OR @TRANSACTION_TYPE='U')
      BEGIN 
			--TO REQUIRED REMARKS  
			IF EXISTS (SELECT DOCENTRY FROM OVPM WHERE COMMENTS IS NULL AND DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR=10
				SET @ERROR_MESSAGE ='REMARKS IS REQUIRED.' 
			END

			--TO CHECK IF CHECK NUMBER EXISTS IN CHECK ISSUANCE
			IF EXISTS(SELECT T0.U_CHECKNO FROM VPM1 T0
			INNER JOIN OVPM T1 ON T0.DOCNUM = T1.DOCNUM
			WHERE T1.DOCNUM = @LIST_OF_COLS_VAL_TAB_DEL AND T1.CANCELED = 'N' AND T1.CHECKSUM > 0 
			AND 
			(T0.CHECKNUM IN (SELECT TA.CHECKNUM FROM VPM1 TA
			INNER JOIN OVPM TB ON TB.DOCNUM = TA.DOCNUM 
			WHERE TB.CANCELED = 'N' AND TB.DOCENTRY <> @LIST_OF_COLS_VAL_TAB_DEL )
			AND
			T0.U_CHECKNO IN (SELECT TA.U_CHECKNO FROM VPM1 TA
			INNER JOIN OVPM TB ON TB.DOCNUM = TA.DOCNUM 
			WHERE TB.CANCELED = 'N' AND TB.DOCENTRY <> @LIST_OF_COLS_VAL_TAB_DEL )))

			BEGIN
				SET @ERROR=10
				SET @ERROR_MESSAGE ='14 - CHECK NO. ALREADY USED IN PREVIOUS TRANSACTION.' 
			END

			--TO ENSURE THAT THE ONLY MANAGING DIRECTOR CAN ADD THE APPROVED OUTGOING PAYMENT ENTRY
			IF EXISTS(SELECT T0.USERSIGN FROM OVPM T0 INNER JOIN OUSR T1
					  ON T0.USERSIGN=T1.USERID
					  WHERE T0.DOCENTRY =  @LIST_OF_COLS_VAL_TAB_DEL AND (T1.SUPERUSER='N' AND T1.USER_CODE !='ACCT1'))
			BEGIN
				SET @ERROR=10
				SET @ERROR_MESSAGE ='ONLY THE MANAGING DIRECTOR CAN ADD THE OUTGOING PAYMENT ENTRY' 
			END

			--TO ENSURE THAT THE DATE ISSUED WAS INPUTTED
			IF (SELECT T1.CHECKSUM FROM OVPM T1 WHERE T1.DOCNUM = @LIST_OF_COLS_VAL_TAB_DEL ) > 0
			AND (SELECT U_ISSUEDATE FROM VPM1 T1 WHERE T1.DOCNUM = @LIST_OF_COLS_VAL_TAB_DEL ) IS NULL
				BEGIN
					SET @ERROR=101
					SET @ERROR_MESSAGE = 'DATE ISSUED FOR CHECK NUMBER IS REQUIRED'
				END
	END

--POSTING DATA, DUE DATE AND CHECK DATE MUST BE THE SAME FOR POSTDATED CHECKS---

IF @OBJECT_TYPE = '46' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OVPM.DOCENTRY FROM OVPM

WHERE 
			
			OVPM.DOCDATE <> OVPM.DOCDUEDATE 
			AND OVPM.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00412
				SET @ERROR_MESSAGE='POSTING DATA, DUE DATE AND CHECK DATE MUST BE THE SAME FOR POSTDATED CHECKS.'
	END 
	END

---INCOMING PAYMENT---

--POSTING DATA, DUE DATE AND CHECK DATE MUST BE THE SAME FOR POSTDATED CHECKS---

IF @OBJECT_TYPE = '24' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT ORCT.DOCENTRY FROM ORCT

WHERE 
			
			ORCT.DOCDATE <> ORCT.DOCDUEDATE 
			AND ORCT.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00419
				SET @ERROR_MESSAGE='POSTING DATA, DUE DATE AND CHECK DATE MUST BE THE SAME FOR POSTDATED CHECKS.'
	END 
	END

--GOODS RECEIPT--

IF @OBJECT_TYPE = '59' AND (@TRANSACTION_TYPE IN ('A', 'U')) 
BEGIN

IF EXISTS (SELECT OIGN.DOCENTRY FROM OIGN
INNER JOIN IGN1 ON OIGN.DOCENTRY = IGN1.DOCENTRY
INNER JOIN OITM ON OITM.ITEMCODE = IGN1.ITEMCODE


WHERE 
			
			OITM.ITMSGRPCOD <> '101'
			AND IGN1.WHSCODE IN ('RVHU WHS', 'SWHU WHS')
			AND OIGN.DOCENTRY=@LIST_OF_COLS_VAL_TAB_DEL)
			BEGIN
				SET @ERROR= 00416
				SET @ERROR_MESSAGE='ITEM RECEIVED IS NOT A SALEABLE UNIT.'
	END 
	END



--PROJECT ACCOUNTING---

IF (@OBJECT_TYPE IN
('DIMENSION','BOQ','SCBOQ','PROJECT','SUBCONTRACTS','ASSETTRANSFER','APRETENTION',
'ARRETENTION'))
BEGIN
EXEC PA_SP_TRANSACTIONNOTIFICATION
@OBJECT_TYPE,@TRANSACTION_TYPE,@NUM_OF_COLS_IN_KEY,@LIST_OF_KEY_COLS_TAB_DEL,@LIST_OF_COLS_VAL_TAB_DEL
END


--------------------------------------------------------------------------------------------------------------------------------

-- SELECT THE RETURN VALUES
SELECT @ERROR, @ERROR_MESSAGE

END