-- PO Under 250K Manager

SELECT 'TRUE'
WHERE $[OPOR.DOCTOTAL] < '250001'
AND ($[OPOR.U_MDAPPROVAL] = ''
OR $[OPOR.U_MDAPPROVAL] = 'N')

-- PO Under 250K Manager/MD

SELECT 'TRUE'
WHERE $[OPOR.DOCTOTAL] < '250001'
AND $[OPOR.U_MDAPPROVAL] = 'Y'